### ISSUE TITLE
Regarding animation with moving window

### ISSUE THREAD

**Issue by usinhampik** [SmileiPIC/Smilei#111]
Dear Developers,

I have a small question regarding animation with moving window. When I try to simulate a propagating beam or a laser pulse using a moving window and plot it using the happi module, the beam and the laser seems to drift in the -x direction for few timesteps and then correct itself. This continues for the entire simulation time.
Please let me know how this can be fixed.

Best,
Ujjwal

**Comment by beck-llr** [comment]
Hi
This cannot be fixed. It is perfectly normal and reflects the way the moving window works in Smilei. The moving window is not performed at everytime step. It is performed when necessary in order to fit the velocity fixed by the user. When the window moves, it moves by a full patch length hence the "brutal" correction you observe. If you want more frequent and smoother applications of the moving window, you need to reduce the patch size along the X direction. But note that this will not change any of the physics of your simulation.
Hope this helps.

**Comment by usinhampik** [comment]
Thanks Arnaud beck
