### ISSUE TITLE
TrackParticle post processing

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#115]
## The problem and the context
I use TrackParticle diagnostic to follow protons accelerated by laser interaction.
My momentum (px,py,pz) were very small. And when I tried to compare spectra between Screen diagnostic and TrackParticle Post processing, kinetic energy was wrong with my calculations from momentum.

## The solution

Momentum of proton in TrackParticle seems to be normalized with mp.c and not me.c because when I multiply momentum by 1836.0, my results are ok (same spectra with TrackParticle or Screen diags).

So I think when you follow a particle with TrackParticle diag, normalization is done with masse to particle * c and not me*c...

**Comment by mccoys** [comment]
I don't know if this is a bug. Maybe a lack of documentation. It is true that the momentum that is given is divided by the particle mass. I am not sure whether we should change the output, or change the documentation.

@MickaelGrech What do you think ?

**Comment by MickaelGrech** [comment]
@juliencelia is right that there is an inconsistency in the momentum between the ParticleBinning and Track diagnostics. In the ParticleBinning, we use the standard normalization which returns momenta in units of m_e c^2. We do not do this in the Track diagnostics, that returns raw data, and it turns out that what is stored in the array particles are the momentum divided by the species mass. 

Now, I would specify this in the documentation, but not change the diagnostics.

**Comment by mccoys** [comment]
Actually, I think that we may need to switch to the correct momentum, because of the OpenPMD requirements.

**Comment by mccoys** [comment]
After some discussions, we decided to modify the outputs of tracked particles. They will be multiplied by the mass. Also, the input of momentum in case of direct particle initialization will be modified as well.

Will close the issue when this is done.

**Comment by mccoys** [comment]
**WARNING**

The latest version now available has the output of tracked particles that are *really* momenta (with the particle mass).

Don't forget to change your analysis
