### ISSUE TITLE
Bug in ParticleBinning smilei version 4.1

### ISSUE THREAD

**Issue by flavorenti** [SmileiPIC/Smilei#123]
## Description

We have found a problem trying to see the pressure tensor in a 2D Smilei simulation, we have printed the pressure using ParticleBinning (see inizialization file attached), but the values printed are around 40 times smaller then the ones expected, the shape is right anyway.

[pressure_bug.txt](https://github.com/SmileiPIC/Smilei/files/3287490/pressure_bug.txt)

## Parameters

- Smilei version 4.1 (also tried with version 3 and there's no bug there)

-sim0 is the one done with Smilei3 (and no bug) while sim0_short was done with Smilei4.1 (bug)

-The pressure obtained from sim0 and sim0_short is different even though there are no differences in the init file, just the Smilei version is different. I suggest that this may be related to the change in weight-particle definition in Smilei4.1, I don't know if you've changed the ParticleBinning routine accordingly to the new weight definition?

##Inizialization files

[KH_simple_init_sim0.txt](https://github.com/SmileiPIC/Smilei/files/3287502/KH_simple_init_sim0.txt)
[KH_simple_init_sim0_short.txt](https://github.com/SmileiPIC/Smilei/files/3287503/KH_simple_init_sim0_short.txt)

**Comment by mccoys** [comment]
Indeed the weight definition has changed, and this has an effect on the outputs of the ParticleBinning diagnostics. However, in the `happi` module, this change has been accounted for (don't hesitate to tell us if you found errors using happi, by the way). If you are using the raw data instead of post-processing using happi, then you must change your analysis scripts accordingly.

We know that changing the weight definition is annoying for users, but it was necessary in order to make weights reusable in other simulations.

**Comment by flavorenti** [comment]
Ok, I was using an older version of happi, that's why I had problems. Thanks a lot
