### ISSUE TITLE
Strange behaviour of fields

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#125]
Dear developers,

We use Smilei4.1. 

The field at 200th timestep shows boundary effects and this effect persists in the further time steps. We have NOT used periodic boundary conditions and the beam is also well fitted within the simulation box.
What could be the reason for this behavior of the fields?

![Ex0](https://user-images.githubusercontent.com/27001896/59596646-6f978180-90f8-11e9-8fc6-868c37064420.png)
![Ex200](https://user-images.githubusercontent.com/27001896/59596647-6f978180-90f8-11e9-8c40-98baf6f9f621.png)
![Rho_electron_beam0](https://user-images.githubusercontent.com/27001896/59596649-6f978180-90f8-11e9-910f-2d7e60fb77e9.png)
![Rho_electron_beam200](https://user-images.githubusercontent.com/27001896/59596652-70301800-90f8-11e9-8cfb-ff16239a6e4d.png)
[filamentation.py.txt](https://github.com/SmileiPIC/Smilei/files/3296311/filamentation.py.txt)

**Comment by Z10Frank** [comment]
Hello, 
thanks for your question!

I am not sure that this intense noise comes from the relativistic initialization procedure, it seems present from t=0 in the zone where the target is defined. I'd suggest some tests:

1. Comment the plasma `Species` definition, and leave only the electron beam, leaving `solve_relativistic_poisson = True`and `solve_poisson = False` (this last one is True by default but it's not necessary when the relativistic one is activated). Also, I would also enlarge transversally the window (at least 6 times). The more energetic the beam is, the more intense will be its field. The transverse fields Ey and Bz will arrive easily towards the borders with a GeV beam like the one in the namelist. This test will show us if the beam creates the intense noise at the right border.

2. Comment the definition of the electron beam and leave only the plasma, with `solve_poisson = False`. I propose this test because I think that the random initialisation of the positions of the electrons and ions can create zones of non neutrality of the charge, which would activate the default `solve_poisson = True` at t=0. The Poisson solver would thus compute an electrostatic field associated to these zones of non neutrality. With the charge at the boundary and periodic BCs in the Poisson solver, it could create strange fields like those you see. Using a `regular` position initialization (with a suitable number of particles per cell) for both `Species` could also solve the problem, since there would not be a charge imbalance (they would be perfectly superimposed).

3. Finally, leave both the plasma and the electron beam, with `solve_relativistic_poisson = True`and `solve_poisson = False`, and using a transversally larger window to accommodate the fields of the energetic electron beam. You do not need to extend the plasma as with the window, probably the phenomena of interest are localised around the beam. You can avoid to simulate particles in the zones too far from the beam by multiplying your plasma density profile by a function that is zero if |y-L/2|>Half_Width_of_Plasma.

**Comment by arsampath** [comment]
Thank you for the detailed response. We will try these tests and get back.

**Comment by arsampath** [comment]
Dear developer, 

We tried your first suggestion. The fields Ex, Ey, Bz still look strange (have boundary effects).
I am attaching rho and Ex at two different timesteps. 


![Ex0000000000](https://user-images.githubusercontent.com/27001896/60018988-0a5e0600-968d-11e9-819d-cf0eea759ab2.png)
![Ex0000000200](https://user-images.githubusercontent.com/27001896/60018989-0a5e0600-968d-11e9-95e9-33ede8418541.png)
![Rho0000000000](https://user-images.githubusercontent.com/27001896/60018999-11851400-968d-11e9-9d30-a5178b4e47fb.png)
![Rho0000000200](https://user-images.githubusercontent.com/27001896/60019000-11851400-968d-11e9-9e13-deacd0d5ad2f.png)

[filamentation.py.txt](https://github.com/SmileiPIC/Smilei/files/3320820/filamentation.py.txt)

We also ran your benchmark simulation tst3d_electron_bunch_wake.py by commenting out the electron species and keeping only the bunch electrons. 
The fields over there also show strange behaviour. Please find the corresponding rho and Ex attached. Please help us understand the reasons for the same. 

![Rho0000000000](https://user-images.githubusercontent.com/27001896/60019316-e0f1aa00-968d-11e9-834d-798c09b66309.png)
![Rho0000000200](https://user-images.githubusercontent.com/27001896/60019318-e0f1aa00-968d-11e9-9401-fb3c5dafb1c6.png)
![Ex0000000000](https://user-images.githubusercontent.com/27001896/60019334-ea7b1200-968d-11e9-90a0-6ab6e3c4d6a6.png)
![Ex0000000200](https://user-images.githubusercontent.com/27001896/60019335-ea7b1200-968d-11e9-81d2-15f6387f3dd9.png)
[tst3d_electron_bunch_wake.py.txt](https://github.com/SmileiPIC/Smilei/files/3320815/tst3d_electron_bunch_wake.py.txt)

**Comment by Z10Frank** [comment]
Thank you for your test.
I think we can conclude that the strange noise at the right boundary was caused by the initialization of the fields of the plasma at the boundary. Unbalanced charges initialised with random position led to fields that interacted with the boundary condition as explained in my first answer. 

Now, in your test the field of the electron beam seems more properly initialised (thanks also to the large window). With a highly energetic beam the field arrives easily at the transverse boundary, generating the reflection effects that you see. There are some approaches to avoid them, for example:

1) Choosing an even larger window, however to make them disappear probably the window will become too large to be practical, even if your plasma has a much smaller transverse extension

2) Adding a plasma as in the benchmark, that partially screens these effects. As you can see leaving the plasma in the benchmarks creates the beam wake fields, which dominate over the fields forming at the boundary. Now you can try the test 2 and 3 to see if your propagation is more proper.

3) Using a perfectly matched layer on the transverse boundary. Unfortunately this is still not implemented in Smilei, and indeed it would be beneficial to simulations where the beam field arrives at the boundary. I hope that it will be implemented soon, and any contribution to the development will be welcome

**Comment by arsampath** [comment]
Thank you for the detailed explanation!
