### ISSUE TITLE
Lorentzboost in SMILEI

### ISSUE THREAD

**Issue by BenK3nobi** [SmileiPIC/Smilei#154]
Heyho, 

I do have another question: 
I want to make a Lorentzboost on a 1-D PIC Simulation in transversal direction. 
I found the Lorentzboost function in Species.cpp

Is it somehow possible to access the boost via the input file? 
The goal would be that I can call a Lorentzboost function with the specific velocity information from the input file. This boost should than be applied on the current momentum distribution?

My current approach would be to write a function in python that does that already and gives the correct momentum values as specific array to SMILEI. 

Is there a "good" way to do such a thing with the currently implemented functions, or shall I do this from scratches? 

Cheers,
Benedikt

**Comment by beck-llr** [comment]
Hi
You can use `mean_velocity` to give a mean velocity to your species along any direction you want.
This mean velocity is not simply added to a previous distribution but uses a relativistic composition.

It should be enough to do what you want if I understand your question correctly. If I don't, please explain clearly what you mean by a Lorentzboost because there is no Lorentzboost function in Species.cpp.

Cheers
Arnaud

**Comment by BenK3nobi** [comment]
Hello Arnaufd, 

thanks for your answer. I have totally overseen the mean_velocity parameter. I thought it would overwrite the distribution, but I can not reproduce why I thought so. 

There is actually a Lorentztransform in Species.cpp. (Starting at line 511 for non massless particles) Lorentztransform is -- with the correct parameters -- the boost I am looking for. 
So this actually solved my issue. 

Thanks a lot again. 
Cheers, Benedikt
