### ISSUE TITLE
kinetic energy and moving window

### ISSUE THREAD

**Issue by T069** [SmileiPIC/Smilei#162]
I try to plot the kinetic energy of an ion layer moving forward. I have to work with the moving window option, so I implement a new axis in the Particle Binning:

```
DiagParticleBinning(
                    deposited_quantity = "weight_ekin",
                    every = 5,
                    time_average = 1,
                    species = ["ion"],
                    axes = [
		            ["ekin",    1,    3000.,   100, "logscale"],
		            ["moving_x",  0.,  18.*l0, 100]
	            ]
)
```

The problem is, that the plot looks like a superposition of many other energy spectra for one time step (which is not the case when switching the moving window off).

I plot the data with this code:

```
PartDiag = S.ParticleBinning(diagNumber=0,timesteps = timestep_e)
ekin = np.array(PartDiag.get()["ekin"])
n = np.array(PartDiag.get()["data"][0])
plt.xscale('log')
plt.plot(ekin,n*weight,color='b',label='Ion energy spectrum',lw=2)
```

As I do not found any Information about this in documentation, I would like to know why one has this behaviour and what are the right peak/spectra of one time step when working with the moving window.

Thank You

**Comment by mccoys** [comment]
I am not sure I understand what you need, but it might be that you misunderstood the particle binning process.

You specified a 2D grid: one axis is the energy in logscale, the other one is the x coordinate (following the window movement). Note that the latter only makes sense of you have specified the MovingWindow block. I guess you did these two axes in order to have 100 distinct energy spectra, one for each x coordinate. What I don't understand is why you put weight_ekin as the deposited quantity. This will sum the particles energy in each bin of energy, which is strange. To have a spectrum, you need the number of particles in each bin of energy. This means the deposited quantity should be weight.

If what you want is simply an energy spectrum, then use only one axis (ekin) and deposit weight.

If you want the average kinetic energy of ions as a function of x, use one axis (x or moving_x) and deposit weight_ekin. This provides the sum of energies. You need a second identical diagnostic with the deposited quantity weight. Then divide the result of the first with that of the second in order to obtain the average energy. In happi, this is easy to do:
`S.ParticleBinning(diagNumber="#0/#1").plot()`

**Comment by T069** [comment]
I only want the energy spectrum, so your first guess was right.

However, if I do it with only one axis and track the ion layer with the moving window, I do not get any ion spectrum after a certain time step (but it should be one displayed for the all simulation time steps). That is why I brought the moving_x axis in it. But if I understand you right, the kinetic energy should work fine with the moving window system and should track the energy of the ions in the moving window (and not in the non moving frame) without any additional arrangements in the particle binning block?

If I plot the ion density in later time steps, the density is correctly displayed with the moving window, but for these time steps, I do have any energy spectrum (for only one ekin axis). So, what could be the problem?

**Comment by mccoys** [comment]
Alright I just found a bug in the particle binning diagnostic. The boundaries are not updated with the moving window. This is why the spectrum disappears. I will fix it ASAP

**Comment by T069** [comment]
Thank You :+1:

**Comment by mccoys** [comment]
@T069 This has been fixed. Could you update and verify if it works for you ?

**Comment by T069** [comment]
This works now fine. Good job!
