### ISSUE TITLE
3D simulation with moving window crashes

### ISSUE THREAD

**Issue by vasimos** [SmileiPIC/Smilei#173]
## Description

Hello,

One of my 3D simulations repeatedly crashes on occigen. It seems that the problem occurs as soon as the moving window starts to move.

Thanks in advance for the help

```
If available, copy-paste faulty code, warnings, errors, etc.
```
I get this kind of error message: 

slurmstepd: error: Exceeded step memory limit at some point.
slurmstepd: error: Exceeded job memory limit at some point.
srun: error: n3168: tasks 16-17: Out Of Memory

## Steps to reproduce the problem

I include the input deck, submit script and log file. For the compilation I used the presets for occigen. 

## Parameters

- Smilei version ? Tried v 4.2 as well as the latest from git
- Input file ? attached
- Commands or script used to run the faulty simulation ? attached job submission script
- Computing resources 
  - type of computer occigen @ CINES, see submission script for module versions etc.
[input.txt](https://github.com/SmileiPIC/Smilei/files/3729565/input.txt)
[job.slurm.txt](https://github.com/SmileiPIC/Smilei/files/3729535/job.slurm.txt)
[slurm-7507328.txt](https://github.com/SmileiPIC/Smilei/files/3729536/slurm-7507328.txt)

  - OS
  - C++ compiler (to get some information `g++ --version`)
  - MPI version (`mpic++ --version`, `mpic++ -show`)
  - HDF5 version (`h5cc --version`)
  - Python version (`python --version`)
  - ...

**Comment by mccoys** [comment]
The error is very clear. You are out of memory. You should split your simulation accross more processors, or use less particles.

**Comment by beck-llr** [comment]
There could be a strong load imbalance and a very high number of particles located on a single node. Would that be possible ? Having only ten times as much as the theoretical total is a very small margin. Load imbalance can be pretty furious in 3D. With 350 nodes you should be good though with respect to typical imbalance.
Have you used the Performance diagnostics ? This is very helpful to check imbalance and memory consumption.

You've run the same job several time. Does the crash happen at the same time ? Theoretically, it should happen later on 350 nodes than on 120. Is it the case ?

**Comment by vasimos** [comment]
These are LWFA simulations, so yes extreme load imbalance would not be out of the question. Unfortunately I did not use the Performance diagnostic. I could run one simulation with this diagnostic to check if the imbalance is the problem.

Yes, the crash indeed happens later on 350 nodes. 

What strikes me is that if I do not use the moving window and reduce the transverse domain size by a factor of two in each dimension, I can simulate the full domain (which is a factor of 16 longer) in 350 nodes for up to much longer times (factor of 5) without issue (but this is very slow so I cannot finish the simulation). In these simulations the total memory usage should be close to 6TB, so I think that if load imbalance was the issue it would have appeared also here and probably even earlier. This is what makes me think that the issue is connected to the moving window.

**Comment by beck-llr** [comment]
Ok so I do think that the memory diag would show a big spike at some point when the wake closes. Especially with the moving window which is a bit memory hungry. We've had a few leaks with it but it is supposed to be ok now. Nevertheless, the memory requirement roughly doubles after the window starts and I see that the crash does indeed happen not very long after the window starts. This is because the particles vector of a patch is not immediately downsized after a big chunck of particles exit it. Resizing the vectors at all times slows down the simulation quite a bit.

Not much you can do here besides using more nodes. I've never managed 3D LWFA simulations with proper accuracy on less than 500 nodes I think. You could try to use load balancing every 20 iterations instead of 200. That costs nothing and would probably help (at least the computation should be faster).
Another possibiliity would be to use the envelope model if the physics of your case is ok with it. That would tremendously speed up your simulation and definitely solve your problem.

**Comment by Z10Frank** [comment]
Also, if your problem is close to cylindrical symmetry, you can use the azimuthal mode decomposition to considerably reduce the required resources. It works even in cases where the envelope model would not be suited (e.g. very short or tightly focused lasers). 

In case your problem has perfect cylindrical symmetry and the envelope model is suitable, we are working on a cylindrical version of the envelope model, but at the moment it is not released. If it could be of interest for you, let us know and we'll try to release it as soon as possible.

**Comment by vasimos** [comment]
Thanks everyone for your suggestions. After looking more closely into this I found that the density already at t=0 looks very weird, see the attached. I tried to change the trapezoidal density profile to a supergaussian defined through a python function and I still get the same kind of results when I run the code at full resolution and 140 nodes on occigen (attached input.deck.txt). When I run a smaller test case (reduced transverse box size, reduced resolution) on 64 nodes I get a density profile which looks absolutely normal, at least at t=0 (I did not run this case for long time. I attach it as input_test.deck.txt).

Note that if I do not use a moving window I do not see such problems in the density profile.

I think this might be related to the crash.

![ne_0](https://user-images.githubusercontent.com/2751008/66993368-be1b5380-f0cb-11e9-9fb3-be594d65688d.png)
[input.py.txt](https://github.com/SmileiPIC/Smilei/files/3738261/input.py.txt)
[input_test.py.txt](https://github.com/SmileiPIC/Smilei/files/3738264/input_test.py.txt)

**Comment by jderouillat** [comment]
It could just be a minor diagnostic incident at t0.  
Do you observe the same kind of behavior at the following diagnostic timestep ?

**Comment by vasimos** [comment]
Yes, the density looks like this at all diagnostic timesteps.

**Comment by vasimos** [comment]
I did not save E_x, which would be most interesting to look at. E_y looks strange at early times but not at later times. I attach two snapshots of that.

Also I analyzed the memory consumption with the help of Mickael. I attach a figure showing the maximum memory consumption at any given node as a function of timestep (what are the units in this btw?). The window starts at some point between timestep 2754 and 2771. I run out of memory after timestep 2805. I hope this helps
![Ey_1360](https://user-images.githubusercontent.com/2751008/67024077-166e4780-f104-11e9-900e-7e54b8e7724c.png)
![Ey_2040](https://user-images.githubusercontent.com/2751008/67024078-166e4780-f104-11e9-9b52-a25854b1a541.png)
![Ey_2720](https://user-images.githubusercontent.com/2751008/67024079-1706de00-f104-11e9-9931-5515c962e355.png)
![mem_timestep](https://user-images.githubusercontent.com/2751008/67024081-1706de00-f104-11e9-9cd9-4695a2ab056a.png)

**Comment by jderouillat** [comment]
It seems that there is a diagFields problem, maybe a synchronization problem at write time, probes could be an alternative.  

For the memory problem, your plot is letting me think that we are maybe not looking at the good memory (with 10 Go per process there is space before being out of space). It could be a problem of stack limit that the Python layer could reached when we create new particles.  
Regarding the logs of your simulation, your patches are really big : 8 x 24 x 24 . Could you try with smaller, 8 x 8 x 8 ?

Did you try to checkpoint/restart your simulation from the timestep 2800 ?

**Comment by vasimos** [comment]
I tried smaller patches as you suggested (8x8x8) and I now get no diagnostic problems. So this was solved but I am curious how to choose a good patch size, especially if I would ran with more processes.

I also tried to set my moving window velocity to c (up to now I was using the wake phase velocity which is less than c) and the crash problem disappears. So it seems that the issue is related to some problem with the moving window when v<c.

Thanks for all the help!

**Comment by vasimos** [comment]
Hello,
I was wandering if you have investigated this issue further? I still get the same kind of crashes when trying to run larger simulations with a moving window.

**Comment by beck-llr** [comment]
Hi. No we have not investigated 3D simulation with moving window with `v < c` yet. Mostly because we have not been able to reproduce your crashes. The critical point is is to understand how a velocity lower than `c` would cause some form of memory leak ... I am currently running heavy 3D simulations with moving window at `v= 0.99975258` and I have never seen this problem.

But since you still observe this, there must be something we miss. Have you tried looking at the performance diagnostics to check the memory usage as we suggested earlier ? Maybe run the same simulation for two different moving window velocity and see if it makes a difference in memory profile ? For references, in my runs, the memory usage for a given MPI rank can peak at a value 10 times higher than the average.

**Comment by vasimos** [comment]
Hi Arnaud,

Thanks for your answer. I should clarify that my simulations crash even when the moving window has v=c, so this was probably not the main cause of the problem.

I have performance diagnostics which are similar to what I have shown above. By the way what are the units of S.Performances(raw='memory_total')?

I will try to increase the number of nodes as much as possible and see if this helps.

**Comment by beck-llr** [comment]
Thanks for the clarification. That makes sense ! So we're just down to a peak memory usage I guess.  I think we should work on limiting those peaks in memory (they're especially bad when the moving window is activated apparently) but this is not an easy task actually and not many users are facing this problem.

As for the units, I don't know ! This is a question for @jderouillat.

**Comment by jderouillat** [comment]
Units are "Go", values are extracted from the system.  
It's the `RSS` (resident set size) of the process read in the system.

**Comment by jderouillat** [comment]
We worked on the memory usage few years ago, one thing that we noticed is that the memory from `std::vector`, on which relies particles management in Smilei, is not properly released while a shrink_to_fit is not operated.  
Without paying attention to this, if all particles goes from one patch to another they are counted twice in memory : of course on the receiving patch but on the emitting patch too (the size of vectors goes to 0 but not its capacity).  
To manage this point, we introduced a cleaning of this particles overhead each `every_clean_particles_overhead` which is 100 by default. It's a parameter of the main block of the namelist, you could try to set it to a smaller value (20).

**Comment by jderouillat** [comment]
@vasimos, could you give us another precision about your crash : when you communicated in October you said that the code ran with `v < c` and patches of size 8 x 8 x 8 cells, finally it crashes with `v = c`, but with which patch size ?
