### ISSUE TITLE
AMcylindrical overestimation of ions energy?

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#179]
Hi Smilei Team,

I work on ion acceleration in gas target.
I did a 2D simulation and I obtain an energy spectrum until about 20MeV for protons...
![spectre2d](https://user-images.githubusercontent.com/48507571/68963279-db306880-07d6-11ea-8864-fe1f862a4ca3.png)

With the same parameters but in AMCylindrical, the spectrum is until 400MeV!!! Perhaps I did an error in my namelist...
![spectreAxisym](https://user-images.githubusercontent.com/48507571/68963394-1e8ad700-07d7-11ea-9257-b3ce6a41c6c0.png)

Here is my namelist
[gasaxisym.txt](https://github.com/SmileiPIC/Smilei/files/3852582/gasaxisym.txt)

And my output:
[out.txt](https://github.com/SmileiPIC/Smilei/files/3852583/out.txt)

Thanks 

Julien

**Comment by Z10Frank** [comment]
Hello,
even when the 2D and AM are both at convergence, it's normal to have different energy spectra, but I don't know exactly how different they should be. Silly question: do the two simulations have the same resolutions?

To  start checking for convergence, I suggest to increase the number of ppc. From my limited experience, ppc=20 is a bit low for AM simulations (start with 50, 100, ...). Besides, if you increase  the number_of_AM to 3, do the results change significantly?

**Comment by Z10Frank** [comment]
PS of course the most accurate estimate of the ions energy would be given by a 3D simulation. At convergence the AM results should be more near to the 3D than to the 2D.

**Comment by beck-llr** [comment]
Hi. I talked with X. Davoine about your problem since I am not familiar with interactions at such high plasma densities. He said that a possible problem is that the early stage interaction of the laser with the high density plasma might trigger a situation far from cylindrical geometry and that potentially many more azimuthal modes could be necessary to accurately describe this physics. He has experienced such problems while simulating TNSA for instance.
That would back up Z10frank suggestion to try more modes and more particles. Remember to use N theta (number of particles per cell along theta) = 4 * N modes.

Have you tried to track the high energy particles in order to understand how they are generated ?

**Comment by juliencelia** [comment]
Hi Arnaud!

I have to work on it. But I notices your advices.
Hope you are OK. 

Julien

**Comment by juliencelia** [comment]
I tried with a number_of_AM = 4, increase ppc = 100 and it's really better (spectrum until 12MeV for protons).
Just have to compare with the 3D simulation.

Thanks for all.

Julien

**Comment by beck-llr** [comment]
That's really good to know. Thanks for reporting.

**Comment by Z10Frank** [comment]
Indeed, it will be very beneficial to study ion acceleration, thanks for the update.
