### ISSUE TITLE
Soften Hydrocodes profiles as input in smilei 

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#180]
Hi Smilei Team,

I am always working on ion acceleration with SMILEI in different type of target (gas, CH, ..).

Thanks to Smilei's Python initialization file, It is quite easy to really initialize the PIC profiles (densities, temperatures, velocity, charge) with hydro output. Since the hydro grids and the PIC grids have no reason to be the same, an interpolation have to be done :I use in my case, the function scipy.interpolate.griddata that can accept the parameters "nearest", "linear" or "cubic".

SMILEI runs without any problem with the parameter "nearest". But this kind of interpolation begets "artefacts" in results because initial profiles are not enough smooth... 

![nearest_method](https://user-images.githubusercontent.com/48507571/69128564-e4f2ee00-0aac-11ea-808b-b7f8a827818d.png)

![cubic_method](https://user-images.githubusercontent.com/48507571/69128570-e8867500-0aac-11ea-98da-5516d1d3a2ef.png)

Example of "artefacts" in px-x for protons : several "little" shocks befaure the real shock :
![px_x_pr](https://user-images.githubusercontent.com/48507571/69128646-11a70580-0aad-11ea-916a-aa7638d74d05.png)

AND MY problem is when I use "linear" or "cubic" method, Smilei craches. See my err and log files:

[err.txt](https://github.com/SmileiPIC/Smilei/files/3862656/err.txt)
[hydro.txt](https://github.com/SmileiPIC/Smilei/files/3862659/hydro.txt)

This error occurs on KNL and also on Curta (cluster of Bordeaux university).
Have you got any idea of the problem?

Thank you very much

Julien

**Comment by mccoys** [comment]
Could you attach your input file ?

Cheers

**Comment by juliencelia** [comment]
[gsi.txt](https://github.com/SmileiPIC/Smilei/files/3862890/gsi.txt)

**Comment by juliencelia** [comment]
Hey Fred

I think I found THE problem...

With the method griddata((x_prof, y_prof), z_prof, (x,y), method=**"nearest") , if I check ne(500,500) python gives me a float (0.0146) whereas with parameters "liner" or "cubic" it gives me an array array(0.0146)!
That must be a problem for SMILEI!

**Comment by mccoys** [comment]
ok :)

**Comment by juliencelia** [comment]
I launched the simulation 2h ago... and I'm always at stage "First patch created"... It seems to be very slow.

**Comment by juliencelia** [comment]
on 200 nodes ;)

**Comment by mccoys** [comment]
If your python computing is very slow, remember that it has to be done for every patch ...

**Comment by MickaelGrech** [comment]
Salut Julien!
So, I just had a quick look at your issue and I'll just drop a quick comment.
I have a student here that runs simulation with foam plasmas and he is using a quite cumbersome technique to generate the foam.
Of course, he is using a Python script & initially had it implemented in the Smilei input file.
It turned out to be quite heavy.
I think that maybe the best way for you to proceed would be generate a matrix or data file before running Smilei and then have Smilei load this data file. This way you may save quite some time in your Smilei simulation (in particular as this is quite a light computation you're doing if you do it once, and not as Fred pointed out for every patch).
This will also prevent you from having to import scipy or other libraries that are not always available on super computers.

**Comment by juliencelia** [comment]
Hi Mika!
Yes I thought about that and I think It could be the best solution... A np.loadtxt is quite light.
Thanks

**Comment by mccoys** [comment]
actually, h5py can read very efficiently pieces of a hdf5 file

**Comment by RavaelGit** [comment]
Hi Julien,
I am the student Micka mentioned. Your problem seems really similar to what I experienced. To solve the problem I used a separate python script to build a matrix using numpy.array which contains all the information I need Smilei to have, then I save the matrix directly as a numpy object (.npy). In the actual input file I only use numpy.load to retrieve the matrix.
This reduces greatly the initialization time. 
Keep in mind that each MPI task need to access the matrix so check that you have enough memory to load the matrix.

HDF5 files are better to use for this purpose in my opinion, but the environment I was using did not give me the possibility to use them so I chose .npy instead.

**Comment by juliencelia** [comment]
OK. I tried something else. I did everything at the beginning of my namelist so the method griddata is called juste once and actually species blocks has just to read numpy.arrays! 
Hope it will works ;)

 SMILEI code is in python so I want to enjoy this opportunity ;)

I post my input if that can be useful for someone.

[gsi.txt](https://github.com/SmileiPIC/Smilei/files/3864470/gsi.txt)

**Comment by juliencelia** [comment]
Hi dear Smilei Team,

So I tried to load all the hydro information in an array at the beginning of namelist and just read informations in it after. It works for initialization ... but the simulation stops at first timestep.

If you have an idea... I don't think it's a problem of memory.

Here are my files (log and err, namelist also).

[err.txt](https://github.com/SmileiPIC/Smilei/files/3887817/err.txt)
[gsi.txt](https://github.com/SmileiPIC/Smilei/files/3887818/gsi.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/3887819/out.txt)

**Comment by mccoys** [comment]
Could you try without vectorisation?

**Comment by juliencelia** [comment]
Hi Fred

I try with vectorisation off. It is the same issue...

BUT : when I use the linear method in griddata it works. It's better than nearest method.
I would like understand why cubic method causes this issue...

**Comment by mccoys** [comment]
Ah

The cubic version probably adds many NaNs. You should remove them.

**Comment by juliencelia** [comment]
There is no Nan in my matrix.
It remains a mystery ;)
But the difference between the two methods seems to be very minimal.
So I will use linear method (much better than nearest) because I needs results quickly because experiment on GSI approches ;)

I don't give up and I ll keep you update on this problem!
Thanks for all
