### ISSUE TITLE
SMILEI 4.3

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#185]
Hi dear Smilei team,

I just have one question, could you be more specific about "tracked particles post-processing was incorrect above 20M particles" in last smilei release... Because I did a lot of simulations that corresponds to that case.

Thanks

Julien

**Comment by mccoys** [comment]
Hi,

When you had more than 20 million particles in a single tracked particle file (not your total number of particles) , and your simulation had several processes, the post-processing would make an ordering that was potentially wrong. As a consequence, trajectories might appear broken because they would correspond to another particle.

There was no problem with `sort=False`.

**Comment by juliencelia** [comment]
Thanks for the clarification!
I don't user sort=True :)
