### ISSUE TITLE
Diagnostics slowness on comet supercomputer

### ISSUE THREAD

**Issue by deuterium33** [SmileiPIC/Smilei#187]
Dear Smilei developers, 

I made a comparison of simulation speed between a workstation (where Smilei, openmpi and hdf5 are installed as in the tuto) and the comet supercomputer. 

I am running for instance the benchmark tst2d_04_laser_wake.py.
The workstation have 12 cores, 1 node, 2 threads per core.
For the supercomputer, I use 2 nodes with each 2 sockets and 12 cores per socket (24 cores/node).

One woud expect the supercomputer to be faster. The workstation is actually twice faster. 
However, one surprising thing I noticed is that the supercomputer spent a lot more time on Diagnostics (is it a hdf5 issue maybe? or some problem with the LUSTRE filesystem of comet?) with respect to the time spent on particles, which as in the case of the workstation, should be the main effort.

See attached the outputs for the workstation first and then the supercomputer.
[HEDP_tst2d_laser-wake.txt](https://github.com/SmileiPIC/Smilei/files/3933891/HEDP_tst2d_laser-wake.txt)
[smilei_tst2d_laser_wake.30071574.comet-16-38.txt](https://github.com/SmileiPIC/Smilei/files/3933892/smilei_tst2d_laser_wake.30071574.comet-16-38.txt)

I am running smilei-v4.2 and the respective configurations are:
- workstation: hdf5-1.10.4, openmpi-3.1.3
- supercomputer:  hdf5/1.10.3, openmpi_ib/3.1.4

Let me know if you have any ideas on the origin of this Diagnostics bottleneck for the supercomputer.

Best,
Mathieu

**Comment by mccoys** [comment]
There could be a number of issues

- the case is not large enough so that it cannot be efficient divided in equal parts. This makes potentially a very bad load imbalance, but should not be that much worse for diagnostics.
- the threads are not very well spread among cores. Still should not be a specific issue for diagnostics. 
- the diagnostics are flushed to often so that nothing is buffered. Threads have to wait until it finishes writing. Have a look at `flush_every`
- there could be some options to figure out with the file system. I cant remember exactly, but lustre had some tweaks for writing efficiently from many processes at the same time
- field diagnostics are not recommended with large runs, especially with many processes. Use probes instead. It would be good to remove diagnostics one by one so that we know which diag is faulty

**Comment by deuterium33** [comment]
Thanks for the tips. Before I go more in depth with each diagnostics, can you recommend me one of the benchmarks coming along with smimei or maybe some other typical one that you may provide me that scale good for 24 processors, which is the amount I can use for a direct comparison between the workstation and the supercomputer? Thanks!

**Comment by deuterium33** [comment]
I actually ran some other tests based on the benchmark "thermal plasma" in 3D, increasing the number of cells from 32*dx(dy,dz) to 128*dx(dy,dz) and resolution down to 0.1*Lde. I think this is large enough now to see a parallelization difference. 

**Doing those tests, I realized that "ibrun" that I was using on the supercomputer did not bind correctly the processes.** 

Running instead by specifying the binding with "mpirun -map-by ppr:1:socket --bind-to socket -report-bindings" and having as many MPI processes as sockets, the simulation run now faster on the supercomputer when using more procs than the workstation, as expected.

**Comment by mccoys** [comment]
That seems good. Running on large computers always requires a lot of care and good knowledge of this kind of trick. Usually, your sysadmin should be able to help, but it is however not impossible that you find a bug in the code. You never know.

**Comment by mccoys** [comment]
Please close the issue if it is ok for you

**Comment by deuterium33** [comment]
Thanks a lot!
