### ISSUE TITLE
Poor performance on our cluster HEBBE

### ISSUE THREAD

**Issue by Horymir001** [SmileiPIC/Smilei#208]
Dear developers,

on behalf of our group, I would like to consult with you the issue we have when running Smilei on the Hebbe cluster we are using.
Despite a number of tries, we cannot squeeze out of our machine more than about 60% performance. We checked that all nodes are somewhat busy, so, clearly, the MPI and OpenMP parts are both working without any major problems. After the consultations with the user support of the cluster, we were referred to write to developers.

I attach following information about the cluster and our job. 

1. Cluster information: https://www.c3se.chalmers.se/about/Hebbe/
2. Loaded modules – from our cluster.
[vojho@hebbe2 Hebbe]$ module list

Currently Loaded Modules:
  1) GCCcore/8.2.0                       8) intel/2019a      15) GMP/6.1.2
  2) zlib/1.2.11                         9) bzip2/1.0.6      16) libffi/3.2.1
  3) binutils/2.31.1                    10) ncurses/6.1      17) Python/3.7.2
  4) icc/2019.1.144-GCC-8.2.0-2.31.1    11) libreadline/8.0  18) Szip/2.1.1
  5) ifort/2019.1.144-GCC-8.2.0-2.31.1  12) Tcl/8.6.9        19) HDF5/1.10.5
  6) impi/2018.4.274                    13) SQLite/3.27.2    20) SciPy-bundle/2019.03
  7) imkl/2019.1.144                    14) XZ/5.2.4

3. Required information: RequiredInfo.txt
3. Input file: eColl-2D-test.py
4. Batch script: EC-2D-test.job – the one with the best performance so far.

In the run with the files provided, I connected to the respective nodes and using the top command, I investigated the performance. As expected, I observed two smilei jobs on every node. Interestingly, the characteristic behaviour looks like this:
Node hebbe09-10 – job1 – 800%
Node hebbe09-10 – job2 – 350%
Node hebbe10-1– job1 – 960%
Node hebbe10-1 – job2 – 960%
Node hebbe10-3– job1 – 960%
Node hebbe10-3 – job2 – 960%
Node hebbe10-4– job1 – 800%
Node hebbe10-4 – job2 – 350%

I assume that there must be something wrong

 with communication. However, we cannot crack it. We would be grateful if you could help us somehow to fix it. 

Please, do not hesitate to ask me further questions. 

Thank you very much for any help.

Best wishes,
Vojtěch Horný 
 
[Hebbe.zip](https://github.com/SmileiPIC/Smilei/files/4205111/Hebbe.zip)

**Comment by mccoys** [comment]
It looks like the run is not well balanced, meaning that some nodes have less work to do. You have a trapezoidal profile, so that the front and the rear of the simulation is going to be empty.

This kind of situation should be handled by the LoadBalancing, but it has its limitations. Typically, you need many patches and not too many cores to be able to spread the workload evenly. You might be in a situation where you have too many cores so that some of them will not have work to do.

I recommend you test on a single node first, to make sure that there is no other issue. Then, increase gradually the number of nodes until you find the problem. You can have a lot of information regarding the workload in the Performance diagnostic, so I recommend using it.

**Comment by mccoys** [comment]
I forgot to mention that, in some circumstances, the load balancing is not useful. Instead, you could try the option ``patch_arrangement`` to distribute the patches in lines. This is usually successful with simulations that are somewhat uniform along x or y

**Comment by Horymir001** [comment]
the patch_arrangment option to distribute patches in lines worked well. we are now on 95% of performance, which is fine. Thank you for your advices.
