### ISSUE TITLE
use chirp_profile

### ISSUE THREAD

**Issue by jafarimjafar** [SmileiPIC/Smilei#209]
Hi dear Smilei team,
Many thanks for the Smilei code
I use chirp_profile with LaserGaussian2D but I have an error.
how to use  them  with  together.

thanks

**Comment by MickaelGrech** [comment]
Hi,
I do not think that the `chirp_profile` is available for `LaserGaussian2D`.
I would advise you to use `LaserOffset` (detailed in Sec. **7. Defining a generic wave at some distance from the boundary** of the documentation on [how to define the lasers](https://smileipic.github.io/Smilei/namelist.html#lasers)). This way, you just have to provide the full (i.e. with the carrier) spatio-temporal profilex of the magnetic fields (By and/or Bz).
I hope this helps, if you have more problem please come back to us; but **please** follow one of the template such as 'bug report' or 'feature request', and provide us with your input file and log files so that we can figure out more easily what is and how to solve your problem.

**Comment by jafarimjafar** [comment]
thanks
