### ISSUE TITLE
Synchrotron emission

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#220]
Dear developers, 

I am analysing the emitted synchrotron power spectrum for electron chi ranging from 0.5 to 1.5.

I used Smilei's particle binning and track particle diagnostics to obtain the power spectrum. I see that smilei under-estimates the emitted power at the low energy range and over-estimates (produces a kink) at the high energy range of the spectrum.

Kindly see attached figures. 

![chi0 5](https://user-images.githubusercontent.com/27001896/75816848-3726f900-5d96-11ea-845d-576d64633be5.png)
![chi1 0](https://user-images.githubusercontent.com/27001896/75816850-38f0bc80-5d96-11ea-98a6-2b23e1ec3c99.png)
![chi1 5](https://user-images.githubusercontent.com/27001896/75817456-668a3580-5d97-11ea-9572-ac112f4b3d89.png)

1) Is this behaviour expected in using Smilei? 
2) If so, is it possible to improve this implementation? 

The input file (for chi=1) is attached below. (A slightly modified version of your benchmark input file).
[tst2d_08_synchrotron_chi1.txt](https://github.com/SmileiPIC/Smilei/files/4283433/tst2d_08_synchrotron_chi1.txt)

**Comment by MickaelGrech** [comment]
Hi!
I am very surprised by your results, I have never seen anything like this.
In particular, I do not understand the step-like features in your plots.
In the paper you can find [here](https://iopscience.iop.org/article/10.1088/1361-6587/aace22/meta), we used a similar approach to what you are trying to do here and found quite good agreement between Monte-Carlo methods and other methods building on the (quantum-modified) synchrotron spectrum.
- Could you attach the python script you use to make your figures?
- Did you account for the quantum form (or only the classical synchrotron one) for your analytical plot?
- What do you mean by Smilei tracks? Are you doing the binning yourself on tracked photons?

**Comment by arsampath** [comment]
Thank you for the prompt response. 
I also did not understand the step feature in the plot. 
1) Python script: [spectra.txt](https://github.com/SmileiPIC/Smilei/files/4283844/spectra.txt)
2) Quantum form
3) Yes, I was binning the data obtained from track particle diagnostics.

**Comment by xxirii** [comment]
Dear @arsampath 

I can produce the same figures with my version of the code.

1.  I can see the step-like structure as well and I can see that the size of the steps depends on the table discretization. I will have a look to computation of the photon energy when I have the time. Normally there is an interpolation between table values to smooth this effect.

2. The difference in energy between particle binning and track particles is more surprising. Particle binning is typically what you are doing with particle tracks. A good way to check is to integrate the spectrum and compare with the `ukin` scalar diagnostic.

**Comment by xxirii** [comment]
I have been investigating the step-like issue. It seems to be the consequence of our algorithm to draw photon energy. The algorithm is standard so I wonder if it could happen in other QED PIC codes. I tried a solution that did not completely remove it. It is also clearly due to the cross-section discretization since a more discretized table induces small stair gaps.

I think we never saw this because your number of iterations is small. Due to stochastic effects, this effect is softened due to the broadening of the electron energy distribution. Usually, we perform our QED simulations on a much larger number of time steps. 

Concerning, the energy difference with the analytical solution, I need to have a look to your method with @MickaelGrech who has already done such a thing. It is possible that one our coefficient is different.

I do not have enough time to investigate and propose a correction immediately for the step-like issue. I will let you know when I solve this issue.

**Comment by xxirii** [comment]
I have continued my investigation.

1) About the setp-like structure. It is both the consequence of the cross-section discretization and the diagnostics as well. In my simulation, I always use the `logscale` argument for `chi`, `gamma` and `ekin` spectra. I discover that it clearly improves the rendering of the plot:

![spectrum](https://user-images.githubusercontent.com/17836646/76951163-867b3680-690b-11ea-9190-210578f612fd.png)

```
DiagParticleBinning(
    deposited_quantity = "weight",
    every = global_every,
    species =["synchro_photon"],
    axes = [["ekin", 0., gamma, 256]]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = global_every,
    species =["synchro_photon"],
    axes = [["ekin", 1e-3, gamma, 256, "logscale"]]
)
```

2) Concerning the comparison with theory, I think you are doing something wrong. The theoretical spectrum that you plot from the QED formulae considers that the emitting particles will not loose energy during the simulation. In the PIC simulation, particles looses energy at each iteration so that the simulation spectrum is not representing the initial `chi` that you use for your theoretical spectrum. This explains why the theoretical spectrum overestimates the simulated one. If you want to do this comparison, you need to deactivate directly in the code the loss of energy (particles can emit but can not loose energy, this is a very theoretical situation). Furthermore, you can see in your simulation that the difference between the theoretical and the simulated spectrum increases with time.

**Comment by xxirii** [comment]
Furthermore, when you use this parameter in the namelist:
```
    radiation_photon_gamma_threshold = 2,
```
You tell Smilei to not create a macro-photon if the macro-photon energy is below gamma = 2. This means that the low-energy part of your spectrum is under-estimated and cut. (Nonetheless, this energy is take into account in the Scalar diags).

**Comment by arsampath** [comment]
Dear developers,

Thank you very much for your response.
Please find below some remarks.

1. Step-like structure:
	a) In my understanding, using log-scale only makes the plot look smoother, but it does not remove the root of the step-wise nature of the data, which is likely insufficient data points in the table.
	b) Could you please provide guidelines on how to improve table discretization? 

2. Analytical comparison:
	Test simulations were run for a total simulation time such that only one photon emission is expected. In this case the simulation and the analytical spectrum must match because all electrons have the same chi at emission.

3. Kink in high-energy end:
	In my simulations, I see a kink in the high energy end of the power spectrum. I do not notice this feature in your plot. 
	Did you run the test input file I provided as it as? Or was there any modifications? 
	Note that the kink becomes increasingly big with increasing chi, and at chi~10 it is very prominent.
	This kink is not present in the analytical spectrum.

Thank you for your help.

**Comment by xxirii** [comment]
About the kink, we had this issue before but it has been corrected. You should not have this issue with the last version of Smilei. The kink was due to some photons that escapes the MC process.

To be fair, I run your test and some variants.

We will soon release an upgrade of the QED in the next Smilei version. For the moment, you can generate the tables using Smilei directly. In the future version, this feature is externalized from Smilei and is provided via an external tool. This tool is more efficient than the current version (someone can generate the tables in few minutes on laptop). Furthermore, we will provide in the documentation some link toward pre-computed high-resolution tables as well.

If you can wait, I suggest you wait for this new version. Else, I can send a tar of this beta version.

**Comment by arsampath** [comment]
Dear developers,

I observe the kink even when I use the master version which was downloaded yesterday. 
In addition, it would be helpful if you can explain how to generate the tables using this beta version and provide a tar of the same. 
Thank you for your time.

**Comment by xxirii** [comment]
Dear @arsampath,

You can download the Smilei version with updated synchrotron emission [here](https://framadrop.org/r/5ntZM2aESD#Q7iv5q4E9LgWYdKXA1eBi2F/5Vu/RWPlbJ+3Fluif+c=). Note that the link is valid 7 days.

Untar it where you want then do:
```
make doc
```
to generate the documentation.

There is a dedicated page for the generation of tables at `/build/html/tables.html`.

Basically, you can compile the tool by doing `make tables` in the root of the repository. It will make appear an executable called `smilei_tables`.

How to use this tool is well described in the doc, but you can as well use the `-h` flag to get a small help page rapidly in your terminal.

The tool is parallelized with MPI meaning that you can use it on a super-computer easily. You will need Boost as well (additional dependency). It is usually already installed on super-computers.

I can help you to setup this tool, just let me know.

**Comment by arsampath** [comment]
Dear developers,
Thank you for providing me with the beta version. 

1) The kink at the high-energy is not present anymore. 
2) I think the equation given in the beta-version webpage for integfochi has some typo/mistake. The following equation matches with the table data for me. 
![Screenshot 2020-03-30 at 10 51 27](https://user-images.githubusercontent.com/27001896/77899267-bf58cb00-727c-11ea-8678-b04af62575d5.png)

![Compare_Table_Analytical](https://user-images.githubusercontent.com/27001896/77899427-fa5afe80-727c-11ea-953f-975114ce0fab.jpg)

3)  Comparison with analytical:

The photon spectrum dI/dεγ = εγ dWrad/dεγ is obtained for εe = 1500 mc2 in a constant and uniform magnetic field such that χe = 1. 
The simulation and analytical results must match when the total time of simulation is chosen as ~1/10th of 1/Wrad. But simulation results are less than the analytical expectation. Kindly let me know your comment on this.

![OneTenth_time_test](https://user-images.githubusercontent.com/27001896/77899150-96d0d100-727c-11ea-9750-429a5dccc272.png)

**Comment by xxirii** [comment]
Dear @arsampath,

Concerning the equation used to compute the production rate and the photon energy, it is indeed different in the doc and in the code but it is in fact the same equation written in two different ways.

Equation in the code is the one I use in my thesis whereas the one in the doc is from one of our last paper : https://iopscience.iop.org/article/10.1088/1361-6587/aace22. 

@MickaelGrech and his former PhD student Fabien Niel have done extensive checking about it. To be sure, I have plotted your equation, the one from the doc and in the code together.

![equation_qed](https://user-images.githubusercontent.com/17836646/78148525-3c2ea500-7435-11ea-8f09-2768876c0bf4.png)

There is however a typo in eq. 26 of the doc. There is a 1/\gamma_\pm missing due to `\gamma_\pm * dt = dtau`

I am still exploring why the code is not providing the theory.

**Comment by xxirii** [comment]
Dear @arsampath,

I have recently studied your case. First, I have found a bug in Smilei due to the recent refactoring causing issues when using multiple MPI processes and external tables. This will be corrected very soon in the master GitHub. Consider the version I sent you as buggy.

Then, I have simulated your case with additional modifications to check that I am close to theory:
- In my case, I completely switch off the electron loss of energy due to radiation directly in the code. It includes both the loss due to the photon emission but also the continuous emission  when the particle chi is below the threshold `minimum_chi_discontinuous` given by the user in the namelist.
- I put the threshold `minimum_chi_discontinuous = 1e-4` to use the Monte-Carlo for a broad range of chi.
- In my scripts to plot the figures, I do not artificially normalize the spectrum. I multiply the spectrum by the right parameter so that the units are consistent. This means that for the theoretical spectrum, I take d^N/dtdgamma, I multiply it by the electron density given by the Scalar diagnostic and by the simulation time in physical units. Then I take the particle binning spectrum, I multiply by the simulation volume and by the spectrum energy delta. You can find the methodology in the attached scripts. 

I did the simulation for chi = 0.1, 1, 10. You can see the corresponding figures below:

![synchrotron_chi0 1](https://user-images.githubusercontent.com/17836646/78558318-a7e88780-7812-11ea-9975-261963fd3bae.png)

![synchrotron_chi1 0](https://user-images.githubusercontent.com/17836646/78558368-b767d080-7812-11ea-8e0b-28ca74c8e514.png)

![synchrotron_chi10 0](https://user-images.githubusercontent.com/17836646/78558381-ba62c100-7812-11ea-975e-e208d62664d3.png)

For you I have generated a new tables with a higher discretization of  1024 points. I have used them for these simulations to minimize the step-like effect.

You can see that here I am getting quite good results compared to theory.

[spectra.txt](https://github.com/SmileiPIC/Smilei/files/4438373/spectra.txt)

**Comment by xxirii** [comment]
Let me mention that I will add a test case in 3D that is very similar to what you have done. Here, I have added the following parameter `radiation_photon_gamma_threshold = 0` so that the MC process can produce photons below gamma = 2. Then, I put `minimum_chi_continuous = 1e4` to deactivate continuous radiation. In this case, the radiation reaction is not cut. The following figure is after the first iteration:

![synchrotron_3d_chi1 0](https://user-images.githubusercontent.com/17836646/78565627-783f7c80-781e-11ea-834a-977e43054af6.png)

Please, can you start again your study with my advice (and the last version of the code) and let me know the results.

**Comment by arsampath** [comment]
Dear developers, 

Thank you very much for your time and inputs. I performed my tests with the latest master version. 
The step-like behaviour has drastically reduced with more grid points. 
The photon spectra matches very well with analytical spectra.

Thank you again.
