### ISSUE TITLE
SMILEI optimization depending on IRENE partition

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#239]
Dear SMILEI team,

Hope everybody is fine.
I have a general question: I noticed quite big differences in SMILEI feats depending on which partition of IRENE SMILEI runs... SKL is more efficient than KNL for example.

According to your expertise, others partitions like OCCIGEN or ROME are more similar to SKL or KNL?

Thank you

Julien

**Comment by MickaelGrech** [comment]
Ciao Julien! All is good so far for us & I hope you too are fine!

So, first I wanna point out that it is completely normal that different partitions of Irene give different performances. 
The skylake processors are really awesome, and much more efficient than the KNL ones.

Now, in my experience, the SKL are the best we have so far & Smilei is performing extremely well on the SKL partition.
It does run nicely too (thanks to all the work on vectorization) on the KNL, but the knightlanding CPUs are not as efficient as the skylakes.
Yet, the KNL partition has the big advantage that you can get much more CPU time on it than on other partitions as Smilei is among the few codes that can run efficiently on it.

Concerning Occigen, I did not run on this machine since years now, but what I remember of it is that it was based on Broadwell CPUs, hence older than either SKL or KNL. But I think there was a plan (maybe it has been done by now) to have SKL processors there, in which case I guess it will work as nicely as the SKL on Irene.

Last, there is a new AMD Rome partition on the Irene machine. I think either @beck-llr, @jderouillat or @xxirii have tried Smilei on it as there is a compilation option for it. Do we have some results on performance on this machine folks?

**Comment by jderouillat** [comment]
Hi,
Concerning Intel architectures, you'll find an overview of the Smilei's behavior on the slide 17 of https://indico.math.cnrs.fr/event/2401/attachments/708/790/HPC_strategies.pdf.  
These data have been recorded more than 2 years ago, but it's typical of the current behavior.  
Jean-Zay nodes based on Cascade Lake from IDRIS are not present here, but it's almost at the level of Skylake.  
Note that references times are by nodes, not by cores. 

For AMD Rome, the reference time on a node is 2.8 ns per particle per timestep, the vectorization benefits is smaller (3.6 ns without) because of the instruction set which is AVX2 and not AVX512.
This time must be put in perspective with the high number of cores (128) and the time consumed to run it (2.8 x 128 on rome and around 5.2 x 48 on skl) and with the energy footprint which is very good regarding the number of cores .
A machine file is available, to compile : `make -j 4 machine=joliot_curie_rome`.

An other critical point for this architecture is to use 8 MPI process per node because of its hierarchical memory.

Julien

**Comment by juliencelia** [comment]
Thanks guys!
I asked to DARI some preparatory hours on ROME. I will try to compile and use SMILEI on it.
Thank you for your clear response!

**Comment by juliencelia** [comment]
Hi,

I want to compile SMILEI on ROME AMD. I have an environment for each partition (knl,skl) with different features (HDF5,OpenMPI,IntelMPI depending on partition). Do you advice me a particular environment for ROME AMD?

Thanks

**Comment by juliencelia** [comment]
Ok I found it in machine file. Thanks.
So @jderouillat , I read that ROME presents 2292 nodes with 2*64 cores per node. But I have to limit number of MPI process to 8?
Thanks a lot.

Julien

**Comment by jderouillat** [comment]
I confirm that. This is due to the hierarchical architecture of Rome's nodes.  
To understand this you can use the `lstopo` command on a compute node (not on the frontend which is different) and see the 4 numanodes per processor.  Below an extract of what you will find :
```bash
  Package L#0
      NUMANode L#0 (P#0 32GB)
      NUMANode L#1 (P#1 32GB)
      NUMANode L#2 (P#2 32GB)
      NUMANode L#3 (P#3 32GB)
  Package L#1
      NUMANode L#4 (P#4 32GB)
      NUMANode L#5 (P#5 32GB)
      NUMANode L#6 (P#6 32GB)
      NUMANode L#7 (P#7 32GB)
```

**Comment by juliencelia** [comment]
Compilation worked!
If I well understood, if I want to run a simulation that run on KNL on 200 nodes (with 64 MPI process per node) for the same simulation on ROME I must run on 1600 nodes with 8MPI process per node.It seems to be huge... Or I have to find better compromise between number of threads and MPI process perhaps.
Sorry I have just 60000hours with preparatory access on ROME so I cant do many simulations...

**Comment by beck-llr** [comment]
No you can keep running the same simulation on 200 nodes (which is already a lot!). With 8 MPI per nodes that makes 1600 MPI processes. Make sure to use 16 openMP threads to benefit from all cores.

But why did you use 64 MPI processes per KNL nodes ? The suggested number of MPI per KNL node is 4 ( 4 MPI with 16 openMP threads each to reach the 64 cores of the KNL).

If you really want to use one MPI per core as you did on KNL you have to use 128 MPI processes per node but I would not advise to do so.

**Comment by jderouillat** [comment]
I misunderstood, 8 MPI process per node is the lowest limit regarding the number of MPI process per node for performance. If you want to use 128, you can. With less MPI process per node, performances are considerably degraded.  

If you want to restart a KNL simulation on Rome, use the minimum of nodes (100 nodes), you should be still faster than on KNL.  
If you want to compare KNL and Rome on your simulations, with 100 nodes you'll have a comparable number of cores, it could be interesting regarding core hours.

**Comment by juliencelia** [comment]
@beck-llr Hi Arnaud, sorry I did a mistake. On KNL I use 1MPI process per node and so 64 openMP threads per MPI. Because it seems to work well like that but I will try your suggestion. Besides, It could be cool to have in the documentation a list of suggestions about partitions of IRENE  about MPI/openMP threads ("The suggested number of MPI per KNL node is 4 ( 4 MPI with 16 openMP threads each to reach the 64 cores of the KNL)"). On SKL for example, I am used to have 1MPI per node with 24openMP per MPI. Perhaps it is not the best way to use SKL...

@jderouillat  Ok I understand now what you wanted to explain. 

Thank you to both of you!

**Comment by mccoys** [comment]
We don't really want to make a documentation for each machine ...

**Comment by juliencelia** [comment]
I understand. Actually, it works on ROME. Thanks again to all the team.
