### ISSUE TITLE
Time loop in log

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#245]
Hi Smilei Team,

I have a question about log file. Is it normal that in a simulation I have in 24H only 5000 timesteps and last indicates 1.8e3s?
This simulation contains lots of diags and collisions (ions/e- and e-/e-) are switched on.

Thanks

**Comment by beck-llr** [comment]
Hi
It is difficult to answer to that without actually seeing the logs but this looks terribly like a deadlock ... The code just waits for ever and do nothing because some expected MPI message never arrives.

 In which circumstances did you experience this ? Can you try to relaunch this job for just 45 minutes and see if it keeps deadlocking at the same time ?

**Comment by juliencelia** [comment]
Thanks I try to relaunch it.

**Comment by juliencelia** [comment]
This simulation runs on KNL. So It is not the same issue as #246 .

I try on SKL but not sure it will change something...

**Comment by juliencelia** [comment]
This simulations runs actually on KNL now. Mystery...
