### ISSUE TITLE
Peak density in AMCylindrical Geometry

### ISSUE THREAD

**Issue by arsampath** [SmileiPIC/Smilei#247]
Dear developers,

I was running a script from the benchmarks folder of Smilei 4.4 version.
[tstAM_12_relativistic_electron_beam_field_initialization.txt](https://github.com/SmileiPIC/Smilei/files/4548186/tstAM_12_relativistic_electron_beam_field_initialization.txt)

It contains a gaussian electron beam with a peak charge density of n0*alpha = -0.00315. When I plot the electron charge density using the Fields diagnostics, I see that the peak density (-0.006)  is almost double the expected peak density ( -0.00315).
![FieldRho0](https://user-images.githubusercontent.com/27001896/80532061-e0a3f880-899b-11ea-80c8-bab3185a1df8.png)
A similar result is obtained using Probe diagnostics also.
![ProbeRho0](https://user-images.githubusercontent.com/27001896/80532393-5c9e4080-899c-11ea-8add-7e38a4de78df.png)

Could you kindly confirm if this is an expected outcome? 
Thank you for your time.

**Comment by beck-llr** [comment]
Hi
This is indeed an expected result. In AM geometry densities are obtained by dividing by the cell volume which depends on the `r` coordinate. The cell on axis is a bit different from the other and needs to be assigned an extra small volume in order to conserve the total charge. This leads to what looks like an overestimation of the local charge and current densities on axis but is actually just a consequence of charge conservation. You can refer to https://www.sciencedirect.com/science/article/pii/S0021999101969232.

Nevertheless, we expected we'd have lots of issues like this one and we have already a correction for this that should be available soon and makes diagnostics look better. 

Cheers

**Comment by arsampath** [comment]
Dear developers,
Thank you very much for the response. 
Does this imply that this observation (overestimation charge density on the axis) is only a visualization problem of diagnostics? 
Kindly also inform when the available correction could be expected.

**Comment by beck-llr** [comment]
It is not only a visualization problem in the sens that if you want the integral of the charge density over your domain to be equal to the total charge of the particles you need to have this higher density on axis.
So it is real but it is only a consequence of the mesh singularity on axis. If you projected the same particles distribution on a Cartesian mesh, you would not see this bump in the center.

But since this density is never used to solve Maxwell's equations ( only currents are) it has no influence whatsoever on the physics. This is why we finally decided to modify the projection on axis in order to produce smoother diagnostics even if doing so you break charge conservation. The physics remains the same in both cases.

The improved version is being reviewed right now and should be available before the end of the week in release 4.4.1.

**Comment by mccoys** [comment]
I think it will be v4.5, not v4.4.1

**Comment by arsampath** [comment]
Thank you again for the prompt response. 

A similar issue is observed while plotting Ex: the longitudinal electric field at t>0 of the benchmark input file. 
(tstAM_12_relativistic_electron_beam_field_initialization.txt)

![Ex0000000001](https://user-images.githubusercontent.com/27001896/81055299-b3d67080-8ec8-11ea-97c1-32022e30fb54.png)

Please note that at t=0, the fields look fine.

![Ex](https://user-images.githubusercontent.com/27001896/81055294-b2a54380-8ec8-11ea-9a65-85fe0faa9cc8.png)

Will the upcoming release of Smilei also address this?

**Comment by beck-llr** [comment]
Umm no this appears to be a completely different issue that I was not aware of. It is probably related to the relativistic poisson solver which does not converge for this benchmark. 

Below is what the density becomes now:
![Screenshot from 2020-05-05 17-46-14](https://user-images.githubusercontent.com/4726107/81086123-640f9d80-8ef8-11ea-9407-507a5bac44ea.png)

**Comment by Z10Frank** [comment]
Dear @arsampath , thank you for your feedback!

That benchmark was meant to quickly test only the field initialisation and to compare the initialisation results in cylindrical geometry with those of the correspondent 3D benchmark, without thinking too much about the propagation of these fields, so the Ex field starts to grow on axis up to dangerous levels. If you use `vmin=-1-e7`, `vmax=1e-7` to plot the next iterations, you can see the "correct" Ex field on the background, while the other E components seem correct even while evolving. 

Unfortunately this phenomenon on Ex does not seem easy to eliminate, but it can be limited using a more realistic bunch (larger and with nonzero emittance for example). To initialise it easily with a numpy array, this should help  
[init_bunch_with_numpy_array.txt](https://github.com/SmileiPIC/Smilei/files/4587696/init_bunch_with_numpy_array.txt)

I suggest also to enlarge transversally the window and to increase the number of iterations of the relativistic Poisson solver. To be even lower than the CFL condition, I would try dt=0.2 .
This way, the bunch will start to expand as physically correct, the Jx will be limited and Ex will remain orders of magnitude lower than the radial field Er as it should be, although the artefacts originating from the axis will remain. For beam driven plasma acceleration, for which this field initialisation was developed, it is a reasonable result, since it is mainly Er to play a role in the involved physics. However, if you think that the role of Ex  is not negligible in your setup of interest, more refined techniques should be used.

The correct propagation of a relativistic bunch field is not a simple task, since the bunch will always be quicker than the numerical propagation speed of the wave in a FDTD Yee Maxwell solver, and this initialisation procedure assumes Bx=0, Jy=Jz=0 at the beginning so I don't expect all the components of the field to propagate without artefacts. PML should be used also for the borders. To avoid any related problems, some codes treat the bunch field separately, advecting it with the bunch and recalculating its fields periodically with the Poisson solver procedure as in a tracking code with space charge. 

If you think that the propagation of bunch Ex will be important in the phenomena you want to simulate, we can investigate for more refined (but of course more time consuming) methods to initialise the relativistic bunch fields.

**Comment by mccoys** [comment]
@beck-llr @Z10Frank Was this isssue partly fixed in v4.5. Is there something else ?

**Comment by Z10Frank** [comment]
@mccoys I don't think so, as I have explained, it is not (only) a BC issue

**Comment by arsampath** [comment]
@beck-llr  Thank you updating the charge density visualisation. 
@Z10Frank  Thank you for your detailed explanation. Smilei 2D and 3D Cartesian geometry is presently good for my study.
