### ISSUE TITLE
Temperatures in Smilei

### ISSUE THREAD

**Issue by ywppku** [SmileiPIC/Smilei#277]
Dear developers,

I am using this method (#91 ) to check the temperatures in my simulation.
While the electron temperatures are reasonable, the ion temperatures seem too high.

I guess when I use deposited_quantity = "weight_vx_px" for the ion ParticleBinning diag., since the momentum of ion is also normed by me*c, I should divide the weight, as well as the ion mass?

In general, I have some questions about the temperatures in PIC simulation, how should we define and calculate the plasma temperature from PIC? 
Using the standard deviation of velocity? Using the pressure divide the density like above? Or to fit the energy spectrum by the Maxwellian distribution of each species?

Since we don't have a temperature diag. in Smilei, do you have any suggestions?

Thanks in advance.

**Comment by mccoys** [comment]
A PIC code is not going to give you a definition of temperature. It will give you some sort of velocity distribution. The diagnostic can sum this distribution in various ways as you noted. But it is your call to find the appropriate definition of temperature for your study.

Concerning the ion mass, it is included in the diagnostic and the momentum is indeed normalized by me*c. There is a mi/me you have to manage.

**Comment by ywppku** [comment]
Dear @mccoys 

Thanks for your timely reply. 

Indeed, the definition of the temperature is not always the same in different studies. 
I guess it is why `happi` doesn't provide a quick check for temperature?

Thanks for the clarification about the `mi/me` factor.
I will close this issue then.

**Comment by prlWanted** [comment]
The temperature is actually a scalar showing that how fiercely the particles move, so it's related to the averaged particle kinetic energy at a certain point. By the method mentioned above, you can have the temperature distribution along the coordinate axis, but usually it's strongly modulated and randomly distributed due to the random instinct of the particles' moving. So I suggest that you also use a SavitzkyGolay filter  to smooth the data and increase the precision without distorting the trend.

**Comment by ywppku** [comment]
Dear @prlWanted 

Thanks for your suggestions. I will have a try of this SavitzkyGolay filter.
