### ISSUE TITLE
Conversion of outputs to OpenPMD

### ISSUE THREAD

**Issue by mccoys** [SmileiPIC/Smilei#3]
This is an issue to list the problems in the conversion to the openPMD standard.
The standard is defined [here](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md), and we aim to include its extension for PIC codes, "ED-PIC", defined [here](https://github.com/openPMD/openPMD-standard/blob/latest/EXT_ED-PIC.md).

General problems
----

- Formatting the timestep by a single integer `%T` is very limiting. Most importantly, there is not padding with zeros to a constant width. Currently, Smilei uses the printf format `%010u`. **In preparation in upcoming standard**
- `timeUnitSI` and `unitSI` are not relevant when the simulation is not absolutely scaled. They should not be required attributes.
- Unclear whether "meshesPath" and "particlesPath" can be the same as "basePath", and whether "basePath" can be simply "/%T/". **Answer: they must be distinct folders**
- ED-PIC: all meshes are required to be in "meshesPath", and this group has some attributes (like `fieldSolver` and `fieldBoundary` and others) that force these meshes to be of the spatial type and basically must all correspond to the simulation box. This is problematic for defining sub-sections of the box, or phase-spaces, or temporal axes, or any mesh that is not that of the simulation box. I guess that all meshes that are not the same as the simulation box are not compliant with openPMD, because by definition, this is all openPMD is supposed to do.

Fields
-----

- ED-PIC: The `particleBoundary` attribute is associated to the meshes, but it should be associated to particles (different for each species). **In preparation in upcoming standard**
- ED-PIC: Fields are forced to be in groups such as `E` which contain the components `x`, `y`, and `z`. This can be inconvenient. For now, Smilei uses the components separately `Ex`, `Ey` and `Ez`.  **Not a problem**
- ED-PIC: The naming of fields that derive from only one species is forced to use the convention `speciesname_fieldname`. This is annoying because Smilei requires the opposite: `fieldname_speciesname` in order to recognize the type of field by its first letter. Furthermore, a species can contain the underscore character, which makes the naming ambiguous. It makes much more sense to reverse. **We'll find a way to accommodate Smilei to that**

Probes
----

Probes are not compliant with ED-PIC's meshes because the mesh is not the same as simulation box. In addition, a mesh storage would not even work with openPMD because they are not always rectangular. The idea would be to store them as particles instead. Still, this has some issues:

- Probes put all the components (Ex, Ey, etc.) in the same dataset, for performance. This is not supported in openPMD.
- The position of probes are defined only once, and stay constant. OpenPMD requires to repeat the positions for each iteration, which would be a huge constraint in memory.

Particle diagnostics
----

- How can we do phase-space meshes, or other? this seems impossible. Even removing the ED-PIC extension (which clearly has all meshes being the same as the simulation box), the standard openPMD does not appear to have anything for phase-spaces, or any other type of mesh. Example: `(x,px)`, `(px,py)`, `(x,p)`, `(x,y,Ekin)`, `(charge)`, etc. **In preparation in upcoming standard**

Tracked particles
----

- Arrays in tracked particles have one axis that is time. This is not supported in openPMD. We could change how smilei stores the data, but the performance result is unclear. More precisely, post-processing particles usually requires to take the info on one particle over time. The openPMD standard makes this very difficult as it requires opening timesteps one by one. **In preparation in upcoming standard**
- How to define particles that are suppressed => not defined in the standard.
- Required ordering by Id => not specified in the standard?

Screens
----

- Same as particle diagnostics, as they contain phase-space data, or similar distributions. **In preparation in upcoming standard**

Scalars
----

We probably could do a single-point mesh for each scalar but this has several issues.

- Scalars would need to be converted to HDF5.
- ED-PIC requires meshes to be the same as the simulation box, which would not be the case.
- Storing one scalar for each timestep in a different group would make a ton of groups, all of them having one value. For simplicity of use, it would be better to have one axis being time, but this is not in openPMD. **In preparation in upcoming standard**

Tool "checkOpenPMD_h5.py"
----

- testing of the `string` attributes seems incorrect: there should be an automated conversion between `[string_]` and `str`. It's too hard to make this within C++, with cross-compiler compatibility. **Check if it is related to variable-length strings**
- ~~The format `/data/%T/` for `basePath` is not mandatory in the standard (it is just an example), but it seems to be hardcoded in the checking. It forbids any other `basePath` argument.~~

**Comment by ax3l** [comment]
Hi @mccoys, thank you for going through the standard carefully and collecting your questions! :sparkles: 

First things first, implementing the *base standard* without the `ED-PIC` extension is sufficient to use most of the tools build around openPMD, such as the `openPMD-viewer`, our `yt-project` frontend and more. So we focus on getting that run first, altough ED-PIC is definitely the goal.

> Formatting the timestep by a single integer %T is very limiting. Most importantly, there is not padding with zeros to a constant width. Currently, Smilei uses the printf format %010u.

Are you referring to `fileBased` `iterationEncoding`? I documented that feature some time ago as a minor improvement that could be added e.g. within `1.1.0`: https://github.com/openPMD/openPMD-standard/issues/121

> timeUnitSI and unitSI are not relevant when the simulation is not absolutely scaled. They should not be required attributes.

That is definitely true and was a design decision, also documented as an *advice to implementers* in the document: https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#advice-to-implementors

Please be aware that as soon as you introduce a laser, ionization effects, collisions, QED effects or anything that introduces an absolute reference scaling, this won't work anyway. Better suggestions then choosing a reference density and adding a comment are welcome, I didn't find one without making things quite complicated to start with :)

> Unclear whether "meshesPath" and "particlesPath" can be the same as "basePath", and whether "basePath" can be simply "/%T/"

No, they need to be disjoint directories. We clarified this part already a bit in the [`upcoming-1.0.1` branch](https://github.com/openPMD/openPMD-standard/tree/upcoming-1.0.1) which contains typo fixes and clarifications. There is also [one more issue open](https://github.com/openPMD/openPMD-standard/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.0.1%3A+Typo+and+Wording+Changes%22) on that topic that will be incorporated in `1.0.1`. Feel free to [look through the issue tracker](https://github.com/openPMD/openPMD-standard/issues) and open up individual questions! :)

> -PIC: all meshes are required to be in "meshesPath", and this group has some attributes (like fieldSolver and fieldBoundary and others) that force these meshes to be of the spatial type and basically must all correspond to the simulation box. This is problematic for defining sub-sections of the box, or phase-spaces, or temporal axes, or any mesh that is not that of the simulation box

Exactly, that's a simplification for now to make post-processing of time series easier. As asked in [this issue](https://github.com/openPMD/openPMD-standard/issues/128) we simply store e.g. phase space information in separate files/directories, since they do not need to fulfill the "ED-PIC" standard anyway. Talking about phase spaces, be aware that there is an other issue for a `2.0.0` update open regarding non-spatial axis: https://github.com/openPMD/openPMD-standard/issues/141

> ED-PIC: The particleBoundary attribute is associated to the meshes, but it should be associated to particles (different for each species).

yep, that's a compromise I made in the first release and it's documented as a defect. In PIConGPU we just assume all species will behave like the first one, "boundary wise", for now which is of course a crude assumption. See https://github.com/openPMD/openPMD-standard/issues/105

> ED-PIC: Fields are forced to be in groups such as E which contain the components x, y, and z. This can be inconvenient. For now, Smilei uses the components separately Ex, Ey and Ez. Not impossible though.

looks just like changing the path to me :) we also store them component wise, we just say "use `E/x` instead of `Ex`" :)

> ED-PIC: The naming of fields that derive from only one species is forced to use the convention speciesname_fieldname. This is annoying because Smilei requires the opposite: fieldname_speciesname in order to recognize the type of field by its first letter.

We started similar years ago and inverted all over the years at least in PIConGPU. It's just a matter of taste.

> Furthermore, a species can contain the underscore character, which makes the naming ambiguous. It makes much more sense to reverse.

Actually not, right-to-left or left-to-right parsing (string splitting) of this record name is in both cases possible and non-ambiguous. Our names are separated from the species by the first from-right `_` so the currently defined [auxiliary fields](https://github.com/openPMD/openPMD-standard/blob/1.0.0/EXT_ED-PIC.md#naming-conventions-for-mesh-records-field-records) are collision free, whatever a user names the species.

> Probes

Can you elaborate on your concept for probes? I know them as non-current depositing particles.
Anyway, you might just want to store those in a separate file/directory similar to phase space output.

> Tracked particles

You could use it's own output file and use `groupBased` `iterationEncoding`. For storing a particle where one record is time (or a field where one axis is time) I unfortunately have to refer to https://github.com/openPMD/openPMD-standard/issues/141 for now.

I am sorry that that case is a bit nasty right now since we wanted to keep things simple first, but it's definitely on the list.

> [other diagnostics]

From PIConGPU we have the experience, that not mixing up the output of various independent "plugins" of our code works best and guarantees more stability. Most cases look like: put them in their own dirs & files and maybe add openPMD markup to those when e.g. non-spatial axis are possible :)

> testing of the string attributes seems incorrect: there should be an automated conversion between [string_] and str. It's too hard to make this within C++, with cross-compiler compatibility.

It's quite likely that this is not a checker defect (report individual issues [here](https://github.com/openPMD/openPMD-validator/issues)) but a writing defect. There is a huge difference between variadic and constant-size strings in HDF5 and other writers, such as ADIOS or let's say a JSON representation would only support the most simple case anyway, which is constant-size strings. It's also not really necessary to allow non-constant size strings, since you know at writing what size your strings has. I elaborated on that requirement a bit [in the first section of the standard](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#conventions-throughout-these-documents), the actual reasoning on it goes a bit deeper, e.g. can variable length strings make *reading* in fixed type language such as C/C++ quite verbose and unpleasant. There was more, I have to look up the ref. on HDF5, but alone the case that we are not limited to HDF5 makes it worth choosing the most simple case, fixed-length strings.

Feel free to have a look into how we implemented both ways in our C++ library [libSplash](https://github.com/ComputationalRadiationPhysics/libSplash/blob/4aa0c039f98295aa75a490ed4fc4df93ae3c9dac/tests/AttributesTest.cpp#L85-L90)

> The format /data/%T/ for basePath is not mandatory in the standard (it is just an example), but it seems to be hardcoded in the checking. It forbids any other basePath argument.

Nope, it's mandatory for now: https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#hierarchy-of-the-data-file

- `basePath`
  - type: (string)
  - description: ...
  - allowed value: fixed to /data/%T/ for this version of the standard

**Comment by mccoys** [comment]
Thank you @ax3l for these detailed answers. I can see there are many upcoming improvements that will be really useful in Smilei.

* Concerning the `unitsSI`, even a laser does not require absolute units. Only a frequency *relative* to a reference frequency, as a laser is basically solving Maxwell's equations. However, collisions, ionization and QED require absolute units indeed. In Smilei, we chose to have an optional argument `referenceAngularFrequencySI` which sets all the quantities absolutely. If it is not defined, our post-processing tools make use of python's [Pint](https://pint.readthedocs.io/en/0.7.2/) package, which has the capability to start in an environment free of any units, but where a list of relative units can be specified. These units are given relative relationships, and Pints figures out how to combine them. We chose, for example, to write the reference velocity *V_r*, the reference current *J_r*, the reference density *N_r*, etc.

* *Probes* are points (or particles if you like, but they don't move) at which fields are interpolated. In fact, they are not single points, but series of points regularly arranged, so you can get local information on fields without burning too much memory. As their position is fixed, it would be good to not repeat that information for every timestep.

**Comment by mccoys** [comment]
@ax3l i have another question. I am still unable to make the strings recognized by `checkOpenPMD_h5.py`. I follow exactly what is done in splash, but the type of string in the h5 file is of type `str` instead of the numpy type `numpy.string_`.

Could it be related to some version of HDF5 or the compiler? Maybe even the version of numpy? Or what about the version of python used to run the script?

Anyways, I do not understand why the type should be that of numpy.

**Comment by ax3l** [comment]
> Could it be related to some version of HDF5 or the compiler? Maybe even
> the version of numpy? Or what about the version of python used to run
> the script?

Thanks for the question!

No, it's just the calls to write the strings via the HDF5 C/C++ API,
"resizable" (dynamic) or static.

For comparison with Python, h5py / numpy also has two ways to do that,
although rather implicit:
```
# static size
f.attrs["staticString"] = np.string_("/data/%T/")

# dynamic size
f.attrs["dynamicString"] = "/data/%T/"
```

Can you point/link me to the file & line where you write your meta data?

Otherwise we can also plan a quick video chat session in the next days,
I thought I have linked the C API call in the libSplash example but I
might find a better example for you.

**Comment by mccoys** [comment]
Ok, there was an error on our side. Sorry. 

Now, how are we supposed to make arrays of variable-length strings? In the base openPMD standard, it seems that no such attribute is required, but some are required in ED-PIC.

**Comment by ax3l** [comment]
In that case it's actually just an *array of fixed size strings*, concatted to a 1D array and padded with `NUL` to be fully `numpy` compatible.

[Python example](https://github.com/openPMD/openPMD-validator/blob/1137a5c55c86bfde8db0db7abf2f000ba9320998/createExamples_h5.py#L186):
```python
meshes.attrs["fieldBoundary"] = np.array(
    [b"periodic", b"periodic", b"open", b"open"])
# ...
B.attrs["axisLabels"] = np.array([b"x",b"y"])
```

C++ [libSplash API example](https://github.com/ComputationalRadiationPhysics/picongpu/blob/3251cab909216de80d91d443802fd87b7d25e6be/src/picongpu/include/plugins/hdf5/WriteMeta.hpp#L243-L250) (with [C++98 helper function](https://github.com/ComputationalRadiationPhysics/picongpu/blob/3251cab909216de80d91d443802fd87b7d25e6be/src/picongpu/include/plugins/common/stringHelpers.hpp#L42-L51)).

```C++
            helper::GetSplashArrayOfString getSplashArrayOfString;

            auto arrFieldBoundary = getSplashArrayOfString( listFieldBoundary );
            ColTypeString ctFieldBoundaries( arrFieldBoundary.maxLen );

            dc->writeAttribute( currentStep, ctFieldBoundaries, meshesPath.c_str(),
                "fieldBoundary",
                1u, Dimensions( listFieldBoundary.size(), 0, 0 ),
                &( arrFieldBoundary.buffers.at( 0 ) )
            );
```

**Comment by ax3l** [comment]
btw, I am sorry the C++ API is still a bit nasty. We are currently designing a new and modern one with a student of ours, to make that process way slicker :)

**Comment by mccoys** [comment]
@ax3l 

We just had a discussion between Smilei developers, but also with other people involved in OpenPMD. There was some consensus around the fact that you cannot force to define the units in SI. This does not make sense in many situations. In fact, it does not make sense either that any viewer requires SI units (it can be a feature though). Is there any plans in OpenPMD to remove this requirement? There is no reasonable way Smilei can support that.

**Comment by ax3l** [comment]
dear @mccoys ,

I think it's best to discuss this question in person, I think it's hard to try iterating it in this issue because I am not involved in your offline discussions.

> [...]not force to define the units in SI

It's not about SI or any unit system in general, but the question if one needs a ratio to an *absolute* unit system. One needs such a ratio as soon as one wants to be able to exchange data *across physical domains* that are not expressed in the same scalings.

Please be aware that openPMD does not force SI, openPMD just wants a ratio to convert to SI. The only thing it forces is: please choose *one reference* so one can convert it to an absolute unit system. That does not mean a post-processing tool can not simply keep the data in a domain-specific unit system, see for example the proposal in https://github.com/openPMD/openPMD-viewer/issues/64 .

I think we need a face-to-face discussion how you would imagine exchanging data *without* an *absolute unit system reference*, e.g. between a PIC code and a particle tracking code or a PIC code and an atomic physics code (those are important applications that need to speak with each other).

> also with other people involved in OpenPMD

Can you forward those people's concrete proposals and the outcome of your offline discussions to me? I am not aware of any proposals yet, the right place for individual proposals would be https://github.com/openPMD/openPMD-standard/issues .

Generally, I would love to find a more slick unit solution without complicating the situation, but need a concrete vision that not just simply drops cross-domain data exchangeability. One could for example allow arbitrary symbols for scalings and allow scaling to an absolute system via an symbol-to-absolute-system-matrix (or skip the latter to make the data not exchangeable outside of a very specific domain).

**Comment by mccoys** [comment]
I'd be happy to have a face-to-face discussion. What is your preferred way?

**Comment by ax3l** [comment]
I would have some time next week if that is ok for you? Can you just write me an email? :)

**Comment by ax3l** [comment]
Thank you for your time @mccoys ! :)

### Meeting Minutes

Regarding the last issue of the reference to an absolute unit system, we discussed that in principle an arbitrarily chosen reference to an absolute system is fine as long as one can express that
- it *was* chosen arbitrarily and
- *how* one can scale the additional degree of freedom *within* the data's initial unit system

We discussed some ideas how to express this, maybe per record or between the unitDimensions and will investigate further for expressive ways.

We also discussed:
- https://github.com/openPMD/openPMD-standard/issues/121 (solution: just use zero-padding already, it's allowed and will likely not brake things)
- https://github.com/openPMD/openPMD-standard/issues/141 (on a high priority for the next major release also for us, e.g. phase space, distributions, calorimeters)
- probes: use external or internal HDF5 references for fixed positions
- path structure: currently set rather static to avoid scattering dozens of attributes per record and heavy meta-data search operations
- updates between openPMD version: readers need adjustments, data updates via automated scripts as long as standard is relaxed (and not "strictened"), otherwise with scripts + user input

**Comment by mccoys** [comment]
After opening openPMD/openPMD-standard#155, I am closing this issue as all the other matters have been answered or are present in openPMD's repo.
