### ISSUE TITLE
"weight" in ParticleBinning diag

### ISSUE THREAD

**Issue by phyax** [SmileiPIC/Smilei#33]
I am wondering how to interpret "weight" in ParticleBinning Diagnostics? In the documentation, it is given as a "number density". Is it counting the number of particles in each bin? But then I found these weights are real numbers instead of integers. So I am guessing there are probably some weighting factors when counting the number of particles in each bin. It matters since I need to determine whether the "weight" in some bins is statistically significant or not. So how should I interpret "weight" in ParticleBinning?

**Comment by mccoys** [comment]
It depends actually (and it is true that the documentation is lacking some explanation).

In Smilei, each macro-particle has a (statistical) weight that is initialized as its species' number density in the cell where it is born, divided by the initial number of macro-particles in that cell. Thus the weight has the dimension of a density. The ParticleBinning diagnostic collects and sums the weights of macro-particle in some user-defined binning. This means that the data written in the `ParticleBinning*.h5` files has the dimension of a density, which is the sum of each macro-particle contribution.

However, as the size of a bin is not the same size as a PIC grid cell, there is some adjustment needed. This is done in `happi` when using the `ParticleBinning` python function. This function returns the particle binning data corrected so that the result is really the plasma number density.  If your binning axes are not only x, y or z, then `happi` also divides by the bin size so that the result can be interpreted as a distribution. For instance, a phase-space binning (x, px) will have the dimension of a number density divided by `m_e * c`.

What is important to recall here is that the raw data in the ParticleBining*.h5 files is not the same as that analysed by `happi`. There is some correction applied.

**Comment by MickaelGrech** [comment]
@phyax hi! 
did @mccoys' answer worked for you?
If so, think about closing the issue ;)
