### ISSUE TITLE
1D simulations with laser at an angle

### ISSUE THREAD

**Issue by cdavidson-strath** [SmileiPIC/Smilei#334]
Hi there,

I just wanted to ask a quick question. Is it possible to perform 1D simulations, where `Main()` geometry is set to 1D Cartesian, and have lasers incident on a target with an angle? I've tried a `LaserGaussian2D` profile with 45 degrees incidence however, the max electric field would suggest I missed the 1D target. The simulations work fine when I use a `LaserPlanar1D` however, I can't get this to work with an angle of incidence. Am I missing something?

**Comment by mccoys** [comment]
`LaserGaussian2D` is for 2D geometry only

The 1D geometry assumes there is no variation across y and z, so this is in contradiction with having an angle of incidence

**Comment by cdavidson-strath** [comment]
I understand and worried about that too. I'm trying to replicate results from a 1D3V PIC code, which had a laser with an angle of incidence. So in order to replicate this in Smilei I would assume I need to be in 2D at least.

**Comment by mccoys** [comment]
I don't see how to have an incidence angle in 1D. There is, however, the possibility of considering a simulation in a Lorentz-boosted frame (transversely). This means that you make normal-incidence simulation, but you Lorentz-boost the results of the simulation so that the observation frame is such that the laser appears at an angle. This is hard to do, but not impossible.

**Comment by Guilleaumes** [comment]
Hi @cdavidson-strath 

As @mccoys said, 1D3V simulation (Smilei along x in Smilei) force translation symmetry for the transverse axis (y and z axis in Smilei) and for that reason angle of incidence is not authorized in this geometry. It's intrinsically a 2D problem. But you can 2 two things :
- Run a 2D simulation with and angle of incidence and mimic a plane wave with an hypergaussian spatial profil. Locally at the center of the hypergaussian spatial profile, the wave will be a "plane-wave" hitting an infinite plasma with an angle of incidence.
- Run a 1D simulation in a Lorentz boosted frame : With a proper lorentz boost in y or z you can mimic an angle of incidence.

**Comment by MickaelGrech** [comment]
There is actually a well known trick to run 1D3V PIC simulations that mimic a laser impinging onto the target with a non-zero angle of incidence. It relies on a Lorentz boost in the y-direction by a velocity vb = c sin(theta). Indeed, if you consider a laser impinging onto a target with an angle theta in the lab-frame, in this new frame (let's call it the Bourdier frame), you can see that the laser is striking the target at normal incidence. 
The original paper describing this technique is available here : [https://aip.scitation.org/doi/10.1063/1.864355](https://aip.scitation.org/doi/10.1063/1.864355). 
It is a pretty widely used technique, especially for guys interested in high-harmonic generation from solid targets: see, e.g., Sec.3 of [this paper](https://iopscience.iop.org/article/10.1088/0953-4075/43/21/213001).

**Comment by Guilleaumes** [comment]
You can find here my PhD Thesis, where I speak about this frame too : https://hal.archives-ouvertes.fr/tel-02956869/ (page 103 Chap 5. Okay it's in french by you can rely on the equation and the paper cited by @MickaelGrech)

In particular, you can do this boosted framed in 1D geometry and in 2D geometry. You can compare the results.

In 2D you have to paid attention in Numerical Cherenkov and Numerical Cherenkov Instability because of a plasma drifting on a grid.

**Comment by cdavidson-strath** [comment]
Thank you all for the comments and advice. I will definitely look into Bourdier paper and using Lorentz transformations for this situation.
