### ISSUE TITLE
smilei input configuration for magnatron with plasma inside

### ISSUE THREAD

**Issue by amircogan** [SmileiPIC/Smilei#340]
Dear,

We would like to simulate a 3D cylindrical plasma with external magnetic field that is created by a solenoid  with alternating current. We also have a grid with potential on it. The plasma that is created is used for etching on a known conductive surface. 
Can this function be simulated with smilei ?
If yes, can you recommend the best input file to use ? 
Any other tips are highly appreciated. 
Thank you in advance !!
Amir

**Comment by mccoys** [comment]
Are you sure you need an electromagnetic code ? Would electrostatic be sufficient ?

**Comment by amircogan** [comment]
It is a long time pulse in the solenoid, so we need the solution of all Maxwell equations.

We need something similar to xoopic but also including external magnetic field time dependent and probably to be real 3D. 
As in xoopic we need ability to add conductor electrode walls with potential we can set.
Thanks

**Comment by mccoys** [comment]
There are time-dependent fields available, but they are unphysical because they are not self consistent. I am actually not sure how this can be done properly. We do have what we call "antennas" which are extra currents. They could be put in the form of a solenoid, but they must be contained in the box. There must be a way to put such antennas on the boundaries to reproduce any field , although I have never seen it done.

To set electric potential at some locations, I recommend setting a few charges with very high mass so that they don't move.

Smilei can do full 3D.

I am not sure about the etching stuff.
