### ISSUE TITLE
MPI_Iprobe issue with collisions

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#352]
Dear SMILEI team,

I had problems with a big simulation in 2D. I came back to 1D simulation.
And without collisions block in the mainlist the simulation runs. With the same mainlist but with collisions activated, I have an issue of MPI_Iprobe.

Have you got an idea?

[BNH1d.txt](https://github.com/SmileiPIC/Smilei/files/5810191/BNH1d.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/5810192/err.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/5810195/out.txt)

Thanks.

Julien

**Comment by jderouillat** [comment]
Hi Julien,
Can you try something like in this [post](https://github.com/SmileiPIC/Smilei/issues/307#issuecomment-705411126) :
```bash
$ export MPIR_CVAR_CH4_OFI_TAG_BITS=25
$ export MPIR_CVAR_CH4_OFI_RANK_BITS=14
```
Regards

**Comment by jderouillat** [comment]
Be careful, it seems that you are using an old release `Version : v4.4-706-gb5c12a5a-master`, while 4.5 has been released in May 2020 and this bug discussed in October 2020.

Moreover, you are using 3840 (240 MPI x 16 oMP) cores for 1024 patches.

**Comment by juliencelia** [comment]
Hi Julien

Thanks I will reduce the number of MPI processes.
One question, sorry but I am always a bit puzzled with the number of patches related to the number of processes: which configuration seems to be the best : how many particles by patch? how many patch for each openMP ?

Thanks again

Julien

**Comment by juliencelia** [comment]
It runs just using the last SMILEI version!
Thanks again.

**Comment by jderouillat** [comment]
I'll answer for the number of patches per thread OpenMP : at least one ! Else, for now, some threads will not have computation to do.  
But if the simulation is imbalanced, the starting target for the number of patches per thread should be 10.  
More you have patches, more the computational load will be smoothed ... But too many patches can produce useless synchronization overhead, that's why I consider 10 as a starting point.
