### ISSUE TITLE
normalized electromagnetic energy

### ISSUE THREAD

**Issue by afzalraghavi** [SmileiPIC/Smilei#369]
Hello dear Smilei developer team,
I'm trying to convert the normalized electromagnetic energy of a laser pulse (Uelm) to real units. The parameters of the laser pulse are as follows:
laser_fwhm = 110e-15m, laser_waist = 50e-6m , lambdar = 800e-9m, Power = 2800TW
The normalized Uem for this pulse is 1.8e10^6, as Smilei output gives.
The normalization factor in header of Uelm graph is K_r.L_r^2.N_r which for my parameters is approximately 2.4
But this factor doesn't give the correct value for the real pulse energy. Should you let me know where I am wrong?
Sincerely yours.

**Comment by mccoys** [comment]
Hi
This type of units is explained here: http://www.maisondelasimulation.fr/smilei/units.html#quantities-integrated-over-the-grid

`Uelm` is not an energy in 2D (only in 3D). The issue is that, in 2D, there is missing information in the 3rd dimension. The code does not know the size of the laser spot in the 3rd dimension. In the end, you will obtain an energy per unit length.

I suggest you do not try to compare energy, but intensity. If you really need energy, then compare to the real-world energy per unit length.

**Comment by afzalraghavi** [comment]
Thanks you very much. I got it.
