### ISSUE TITLE
Screen normalisation to compare with experience

### ISSUE THREAD

**Issue by lesnat** [SmileiPIC/Smilei#39]
Hi,
I come to you because the way Smilei is calculating the sum of weights in Screen diagnostics, and the way to get a physical number of particle from this diag is still not very clear in my mind, even after reading [the documentation](https://smileipic.github.io/Smilei/post-processing.html#units-of-particlebinning-and-screen).

For the context, I'm actually doing 1D simulations of laser-solid interaction, and get the electron weights in function of their kinetic energy on a screen diagnostic inside the target, then put this source term in a Monte Carlo code and get the results I want to compare with some experiments. 

For this I need to understand how to normalise the screen output in order to get a number of electrons,  not a density ; but I don't know which length I may use in longitudinal direction (on transverse direction I take the surface of the beam spot as a typical surface).

Some people also told me that for 1D PIC simulations, the diagnostic outputs should be in number of particle per unit of surface, because there is a lack of information on the two transverse directions. For 2D, outputs should be in number of particle per unit of length, because information are known in 2 directions and 1 direction is unknown.
The weights calculation are probably different in their case, and for going to these units I only need to multiply my output by a length in longitudinal direction.

I think I understand that if the diagnostic is the sum of weights in function of one space direction (so density in function of space) the bin size is the length to choose, because the sum is done over the whole bin and then the number of particles in this bin will depend on its size.

However, I can't choose the cell length as a longitudinal length with a screen diagnostic, because it does a sum of all particle weights passing through **one single place** and so my normalisation would strongly depend on the spatial resolution I choose for my simulation, which is clearly not physical.

I did some tests with the simulation length as a longitudinal length. I ran my simulation with different sim length (and adapt sim time for considering the same interaction time) and get these results :
Output in $N_r/MeV$:
![var_lsim](https://user-images.githubusercontent.com/24250367/34838787-b2f91428-f6ff-11e7-926d-b08bd4133990.png)
I was firstly surprised that the results were different for different sim length, but probably I shouldn't be.

I tried after that to multiply the output by the critical density, my sim length (in meters), and the focal spot surface (in meter squared), and get this result :
Output in number of e-/MeV:
![norm_lsim_x_waist2](https://user-images.githubusercontent.com/24250367/34838811-c183e270-f6ff-11e7-8729-fe40db3e931c.png)

This looks like really better.

If I multiply instead by the total number of cells I would get the same agreement between these 3 curves (because I divide all outputs by the same cell length in meter, but here I get a problem with units). So I need to get a confirmation that multiplying by the simulation length it is the right thing to do, and I would like to understand why.

Putting this apart, I also did some tests about particle_per_cell number, and found that the neutrality condition between electrons and ions have not to be respected for getting good results, if this neutrality condition is respected for density. I did not found this information in the doc (that now looks great !), and I think it could be nice to include it because it's a good feature of Smilei :) 

Thank you,
L.

**Comment by mccoys** [comment]
You did the right thing. As stated in the doc, ``The output is divided by the total number of cells in the simulation``. This should give a result to be understood as the *portion* of the plasma density that went through the screen. It also explains why you did get different results when changing the sim length.

This is not a really good number in your case, so you need good normalization. Go back to the definition of the weights: ``the species density divided by the number of macro-particles of this species in the cell where the particle is born``. In short ``W = n/Nppc``. The sum of weights done by the diagnostic eventually gives you ``sum(W) = n`` assuming that this sum corresponded to one cell. In order to get a number of *real* particles, you would need to multiply that sum by the volume of one cell ``Vcell``. On top of that, remember to compensate for the post-processing that automatically divides by the total number of cells in the simulation ``Ncell``. In summary, you need to multiply by ``Vcell x Ncell``, meaning the total simulation volume !

That sounds easy, but what is the simulation volume in 1D ?? As you said, in the ``x`` direction, this is easy: multiplying by the length along ``x`` gives you a number of particles per unit surface. You cannot really go much further if you only have a 1D simulation. To get the transverse surface, you have to make some assumption about "how far transversely" would the 1D simulation still apply. But that's not always feasible.

Concerning the neutrality condition, I don't really understand: you say you do have good density neutrality! So what is the problem?

**Comment by MickaelGrech** [comment]
I would like to build up on @mccoys comments.

First, all "particle number" in a 1D simulation will indeed be a particle number per units of surface (areal density), conversely in a 2D simulation a particle number per units of length (linear density). Hence, to get the real number you have to make an assumption on the transverse size of your screen/source. This can be, e.g. the transverse size of your focal spot and/or much larger depending on what your considering. Once you have this transverse size, you can compute the surface than get to an estimate of the real number of particles.

Second, concerning the neutrality condition. If I get it correctly, you are 'happily' surprised that you need not have as much macro-particles for electrons and ions to ensure quasi-neutrality at time t=0. Is it correct? If this this so, you should not be surprised ;)! The macro-particles are (just) a mathematical trick to solve Vlasov's equation [see Sec. 2.3 of SMILEI's paper]. Rather than real particles, they correspond to 'elementary blocks' of the distribution function. Therefore, nothing prevents you to use different number of macroparticles for different species as long as you can fix different weights for the macro-particles which is the case in SMILEI. As you observed, the only requirement to ensure quasi-neutrality at time t=0 is that your densities (from which the macro-particles' weights are computed) do ensure quasi-neutrality.

**Comment by MickaelGrech** [comment]
Leo, can we close this issue?

**Comment by lesnat** [comment]
Sorry I've wrote a reply few days earlier but it was not clear so I did not post it.

To sum up, I understand that for having a good normalisation for a Screen diag I have to counterbalance the happi operations, so why does happi is applying these corrections ?

I'm also thinking about dimensionality of the input/output. Does the corrections are applied as correction factors ( in units of [meter]/[length code unit] for example ) so have no dimension or have a [length] dimension is this example ? I try to understand what is the dimension of the number_density I'm giving to the code ([length]^-2 or [length]^-3) and if it changes anything on the data treatment. Not really clear in my mind.

**Comment by mccoys** [comment]
Concerning your first question, it is difficult for us to anticipate all the possible choices that users make in their data analysis. We had to make a choice in happi, and the one we made seems the one that would work for most cases.

Concerning units, happi, by default, always uses the code units (see the Units section in the doc). In your case, you have an energy spectrum meaning a density per unit energy. We like to write the code's density units as ``N_r`` and the energy density units as ``K_r``. That means your spectrum has the units ``N_r/K_r``. You may change this units to express them in more common numbers as follows. The easiest is ``K_r`` because it is ``m_e c^2``. The density ``N_r`` is ``ε0 m_e ω^2 r/e^2`` where ``ω`` is your reference angular frequency. For example, it can be your laser frequency if you have a laser defined with ``omega=1.`` in your input file. In this example, ``N_r`` is equal to the critical density.

**Comment by lesnat** [comment]
Ok I understand.
So no matter if my simulation is 1, 2 or 3D, I should give the same `number_density` in my namelist and multiply it by the same reference density for normalisation.
If yes, you can close the issue after your answer. 
Thank you !

**Comment by MickaelGrech** [comment]
Mmm... I'm not sure how to interpret your question.
The density depends on your physical set-up.
If you're considering laser-plasma interaction (which I guess you are) then
the most simple way to do it is to use "laser-related units".
That is, you normalise times to \omega_0 = 2\pi c/\lambda_0 (with lambda_0
the laser wavelength): that is your reference angular frequency is set to
\omega_0.
If you do so, space units are in units of 1/k_0 with k_0 = \omega_0/c and
(number) densities are in units of n_c the critical frequency for an
electromagnetic wave with angular frequency \omega_0.
Whatever the dimension of your problem, densities are therefore defined
uniquely.

Now, if you are in addition interested in radiation processes (radiation
reaction, photon production etc...), you need to define the reference
angular frequency in absolute.
In SMILEI, this is done by giving this reference angular frequency in SI
units by defining the variable: "reference_angular_frequency_SI".
For the case of a laser with wavelength one micron, you could do this as
follows:

import math
c = 2.99792458e8                  # speed of light in SI units [m/s]
lambdar = 1.0e-6                   # laser wavelength in SI units [m]
wr = 2.*math.pi*c/lambdar     # reference angular frequency in SI units
[1/s]

and you have to add in SMILEI's Main() block:
"reference_angular_frequency_SI = wr"

Does this answer your question?

Cheers,
Micka

**Comment by lesnat** [comment]
Ok I get it

> Whatever the dimension of your problem, densities are therefore defined uniquely.

This does answer my question, thank you !
Léo.

**Comment by MickaelGrech** [comment]
Perfect! I close the issue
