### ISSUE TITLE
mask on the wave field

### ISSUE THREAD

**Issue by phyax** [SmileiPIC/Smilei#41]
Hi,
I have a 2D simulation with an open boundary condition for the waves and a reflective boundary condition for particles. In the center of domain, an antenna is launching waves with frequency 0.2 * fce. But the silver-muller boundary condition does not work very well for my case. There is some reflecting waves (see the figure below). I would like to quickly experiment with a mask function that smoothly damps the waves over some wavelengths at the boundary. How can I quickly implement it in Smilei or could you send me a quick implementation of this? Thanks.

![boundary](https://user-images.githubusercontent.com/20483877/35308504-dd8a7a04-005c-11e8-9030-7d34a56ac313.png)

**Comment by beck-llr** [comment]
Hi
The Silver Muller boundary conditions are written to be optimal for either the plasma or laser frequency (not antenna) and for normal incidence only. We are currently working to allow the user to define these parameters himself since we noticed that it can dramatically improve some particular cases. This will be available in the next release and might be enough to solve your problem.
If you share your inputfile we could try to confirm that this will fix your problem or not.

**Comment by phyax** [comment]
@beck-llr  Thanks for your response. In order to confirm if the new feature solves my problem, here I attach the input file.
[trigger2d.py.txt](https://github.com/SmileiPIC/Smilei/files/1659140/trigger2d.py.txt)

**Comment by phyax** [comment]
@beck-llr 
I tried the "thermalize" boundary condition but the reflecting waves did not go away. The field pattern is similar to the figure I showed above. (I note that the thermalize boundary only work for non-relativistic temperatures. So only the warm species is used in the run.)

**Comment by beck-llr** [comment]
The wave has a normal incident on the xmin and xmax border so adjusting the angle won't solve the problem. We are going to try to adjust the frequency of the absorbing boundary but we do not expect this to work either since absorption is correct in the absence of particles.  
If you want to implement new boundary conditions, you can have a look at those that are already implemented in the directory `src/ElectromagnBC/` and follow the same pattern. Do not forget to add your new BC to the factory in `ElectroMagnBC_Factory.h`.
