### ISSUE TITLE
Poisson Solver does not converge in AMcylindrical geometry

### ISSUE THREAD

**Issue by mfrancois999** [SmileiPIC/Smilei#421]
Hello

I try to use cylindrical geometry so I did some tests like adding proton and setting the Poisson solver to "True" in the tutorials "Azimutal-mode-decomposition cylindrical geomatry".
In this case the namelist is like this : 
[laser_wake_AM.txt](https://github.com/SmileiPIC/Smilei/files/6792244/laser_wake_AM.txt)
In this situation the Poisson solver does not converge.
Initial fields setup
 --------------------------------------------------------------------------------
     Solving Poisson at time t = 0
 

 Initializing E field through Poisson solver
 --------------------------------------------------------------------------------
 iteration 1000 started with control parameter ctrl = 327465351257415090176.00 x 1.e-22
 iteration 2000 started with control parameter ctrl = 1323798612721785372672.00 x 1.e-22
 iteration 3000 started with control parameter ctrl = 2078794565126651904000.00 x 1.e-22
 iteration 4000 started with control parameter ctrl = 2687740081668962648064.00 x 1.e-22
 iteration 5000 started with control parameter ctrl = 3243589231562267820032.00 x 1.e-22
 iteration 6000 started with control parameter ctrl = 3777861254599765655552.00 x 1.e-22
 iteration 7000 started with control parameter ctrl = 4337536947515094466560.00 x 1.e-22
 iteration 8000 started with control parameter ctrl = 4823727827276908199936.00 x 1.e-22
 iteration 9000 started with control parameter ctrl = 5355243967284723580928.00 x 1.e-22
 iteration 10000 started with control parameter ctrl = 5808506500981542879232.00 x 1.e-22
 iteration 11000 started with control parameter ctrl = 6293664589629468180480.00 x 1.e-22
 iteration 12000 started with control parameter ctrl = 6723116749328487546880.00 x 1.e-22
 iteration 13000 started with control parameter ctrl = 7193973877708050923520.00 x 1.e-22
 iteration 14000 started with control parameter ctrl = 7655357733702971949056.00 x 1.e-22
 iteration 15000 started with control parameter ctrl = 8182082348596411236352.00 x 1.e-22
 iteration 16000 started with control parameter ctrl = 8651671444498068537344.00 x 1.e-22
 iteration 17000 started with control parameter ctrl = 9039512707168333725696.00 x 1.e-22
 iteration 18000 started with control parameter ctrl = 9541279095714377367552.00 x 1.e-22
 iteration 19000 started with control parameter ctrl = 10018889545479249461248.00 x 1.e-22
 iteration 20000 started with control parameter ctrl = 10360208059353389858816.00 x 1.e-22

I run it with the CELIA custer Theremin with this script : 
[script.txt](https://github.com/SmileiPIC/Smilei/files/6792287/script.txt)

Is there a problem with the way I add protons ?

I apologize for the bother and thank you for your time.

**Comment by Z10Frank** [comment]
Hello, 
have you tried increasing the `poisson_max_iteration`? The default maximum error threshold for convergence is `poisson_max_error=1e-14` (https://smileipic.github.io/Smilei/namelist.html), but it can be increased if convergence occurs before.

**Comment by mccoys** [comment]
This might be a bug. Here is the only AM case we use together with the Poisson solver, `tstAM_13_electron_sphere_field_initialization.py`

```
...
 iteration 43000 started with control parameter ctrl = 120150167480066.265625 x 1.e-22
 iteration 44000 started with control parameter ctrl = 120055290839049.703125 x 1.e-22
 iteration 45000 started with control parameter ctrl = 87186104068066.140625 x 1.e-22
 iteration 46000 started with control parameter ctrl = 67077142048458.390625 x 1.e-22
 iteration 47000 started with control parameter ctrl = 42380196369583.859375 x 1.e-22
 iteration 48000 started with control parameter ctrl = 33009883782526.683594 x 1.e-22
 iteration 49000 started with control parameter ctrl = 35510944556230.273438 x 1.e-22
 iteration 50000 started with control parameter ctrl = 35524430473527.828125 x 1.e-22
	[WARNING] Poisson equation solver did not converge: reached maximum iteration number: 50000, relative err is ctrl = 35523903549758.046875x 1.e-22
	 Computing El from scalar potential, Poisson problem
	 El: done
	 Computing Er from scalar potential, Poisson problem
	 Er: done
	 Computing Er from scalar potential, Poisson problem
	 Et: done
	 Computing El from scalar potential, Poisson problem
	 El: done
	 Computing Er from scalar potential, Poisson problem
	 Er: done
	 Computing Er from scalar potential, Poisson problem
	 Et: done
....
```

@Z10Frank Is this expected?

**Comment by mccoys** [comment]
In fact, increasing the number of iterations to 500000 solves the problem, but in your case I am very surprised as the plasma should be neutral. The Poisson solver should not even go further than 1 iteration.

**Comment by Z10Frank** [comment]
@mccoys how much time does it need for convergence increasing the number of iterations? Maybe the non convergence was on purpose to have a benchmark that did not need too much time for automatic testing. 
In AM geometry the ions may not be superposed to the electrons without a `position_initialization="electron"`, this may create the non perfect local neutrality.

@mfrancois999 we'll investigate, this behaviour.
Meanwhile, for a LWFA simulation where you are not using ionization or investigating ion motion you may turn off the Poisson solver and define only the electrons. This way they will behave as if immobile background ions are present (see section `A subtlety: why ions are not present` here https://smileipic.github.io/tutorials/advanced_wakefield_electron_beam.html). 

If you are interested in having ions, you can turn off the Poisson solver and define the ions with `position_initialization="electron"`, to perfectly superpose them to the electrons (with the same number of particles of course). This way the local charge neutrality should be perfect and the Poisson solver would not be needed.

**Comment by mfrancois999** [comment]
As you suggested I increased the number of iterations to 500000. And even in this case the Poisson Solver does not converge.
iteration 499000 started with control parameter ctrl = 183668510586590245945344.00 x 1.e-22
iteration 500000 started with control parameter ctrl = 184036124739873057800192.00 x 1.e-22
	[WARNING] Poisson equation solver did not converge: reached maximum iteration number: 500000, relative err is ctrl = 184036438287698238636032.00x 1.e-22

And after I've had this a hundred times
         Computing Er from scalar potential, Poisson problem
	 Er: done
	 Computing Er from scalar potential, Poisson problem
	 Et: done
	 Computing El from scalar potential, Poisson problem
	 El: done
	 Computing Er from scalar potential, Poisson problem
	 Er: done
	 Computing Er from scalar potential, Poisson problem
	 Et: done
	 Computing El from scalar potential, Poisson problem
	 El: done
	 Computing Er from scalar potential, Poisson problem
	 Er: done
	 Computing Er from scalar potential, Poisson problem
	 Et: done

and this error

#6    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#5    Object "smilei", at 0x45871e, in 
#4    Object "/usr/lib64/libc.so.6", at 0x2b90bec95554, in __libc_start_main
#3    Object "smilei", at 0x457ffe, in main
#2    Object "smilei", at 0x6611d2, in VectorPatch::runNonRelativisticPoissonModule(Params&, SmileiMPI*, Timers&)
#1    Object "smilei", at 0x660573, in VectorPatch::solvePoissonAM(Params&, SmileiMPI*)
#0    Object "smilei", at 0x64d980, in void SyncVectorPatch::exchangeAlongAllDirectionsNoOMP<std::complex<double>, cField>(std::vector<Field*, std::allocator<Field*> >, VectorPatch&, SmileiMPI*)
Segmentation fault (Address not mapped to object [0x112])
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

**Comment by Z10Frank** [comment]
@mfrancois999 Thank you, I have run some investigations as well.

My conclusion for the moment is that with the resolution and number of grid points that you have chosen the "Poisson's matrix" to be inverted is ill-conditioned, giving rise to a divergence of the control parameter that you see, a sign that the solution is not converging. The ill conditioning does not depend on the solver, it is an intrinsic characteristic of Poisson's matrix without preconditioning, i.e. the matrix obtained through discretisation with Finite Differences of Poisson's equation.

If you use `number_of_AM=1`, a `dx` eight times larger and dividing by 8 consequently the `nx` and the number of patches along x you will see that the solver converges. Using a factor 4 instead of 8 will give convergence, but slower. A factor 2 and factor 1 (i.e. your mesh) yield divergence. With smaller cell size and larger number of mesh points the matrix to be inverted becomes more sparse, more ill-conditioned and thus more difficult (if not impossible) to invert with any iterative (or direct) solver without more sophisticated techniques. To cope with this problem the code already has a form of preconditioning to help convergence, but it does not work for all choices of mesh. Maybe a more sophisticated preconditioner matrix would work, but we'll need some research and some time to implement it. Yesterday I have made some tests with different preconditioning, but with no better convergence rate.

Increasing the `number_of_AM` in this case makes things worse, because the matrix associated to mode=1 is even more ill-conditioned and the source term is almost zero (your charge distribution is mainly represented by mode zero), so even with a factor 8 as before the solution for the mode 0 converges, while the mode 1 diverges.

Since the mesh altered with a factor 8 or 4 (and using only one azimuthal mode) is not suited for a simulation with a laser without envelope as in your namelist, I suggest to turn off the Poisson solver and avoid having an imperfect charge imbalance. As mentioned in my first answer, keeping only the electron `Species` and turning off the Poisson solver will make the simulation behave as if there was a layer of neutralising immobile ions. This works well for most LWFA simulations. If you are interested in ion presence or motion (e.g. for ionisation, but I don't see it in your namelist), you can perfectly superpose the ions to the electrons putting `position_initialization="electron"` in their `Species` block. This way the local charge neutrality will be perfect and the Poisson solver will not be needed. Of course for a standard laser you will need `number_of_AM=2`.

Do you think that these solutions could work for your case?

**Comment by mfrancois999** [comment]
Keeping only the electron and turning off the Poisson solver like you suggest works in my case.

Thank you for your time and your advise
