### ISSUE TITLE
neutron missing in DD reaction

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#433]
Hi Smilei Team,

I'm trying to use the experimental nuclear reaction options. (version 4.6-237)
While some H3 are created it appears that no neutron are reported in the number density map.

Moreover, bad declaration of neutron species do not prevent the reaction:
atomic_number=charge=0,atomic_number=charge=1, atomic_number=0 charge=1

only atomic_number=1 charge=0 returns an error

For more types of nuclear reactions (and avoid confusions) may I also  suggest to add the posssibility to set the species by their proton/neutron numbers.

[nuclear_DD.py.txt](https://github.com/SmileiPIC/Smilei/files/6938056/nuclear_DD.py.txt)

**Comment by mccoys** [comment]
Hi

1) Neutrons are not created because they do not participate in the current. For now, we chose to not create neutrons as they would only use computation power. To count the number of neutrons you can simply count the number of He. If you have a specific reason you need neutrons, please explain why.
2) `charge` is not accounted for in nuclear reactions. Only atomic number and mass (see the doc, where it is indicated).
3) Setting the number of protons/neutrons is possible, but it would add other parameters in the input file, which is not really good for clarity. You can easily compute the mass and atomic number from number of neutron/proton with a python script.

**Comment by ccaizergues** [comment]
Hi @mccoys 
I am primarily interested in other reactions, involving protons.
So I am concerned if the present implementation could be soon extended to other channels (in principle it might only require new cross-sections, but i may be more complicated if there are too many specific treatments related to neutrons).
The charge should then be accounted for, to distinguish the various possible channels as well as the number of nucleons.
Although the variation of atomic masses is small enough to distinguish isotopes from only mass and charge (even with rounding errors on nucleon masses in python script), this may be not fully practical (or computationally efficient).

For the neutrons usefulness, of course, they could further react in targets.
What is still « experimental » in present version of Smilei ?

**Comment by mccoys** [comment]
Concerning other reactions, people at Celia are implementing proton-boron types of reactions in Smilei. It is technically very easy to add neutrons anyways in the current implementation so I am not worried.

Concerning the charge, I am not sure I follow. In Smilei, the `charge` is not the nucleus charge, but the overall atom charge, which may be zero for any type of atom for instance. That's why it is not accounted for during nuclear reactions. The atomic number is the number of protons, thus if you know the mass you can deduce the number of neutrons without any confusion. You simply divide by the atomic mass unit.

The "experimental" mention could be removed, but I was waiting for more people to test and give feedback (thank you by the way!). One thing, for example, that could be done, is to give the option to create the neutron or not.

**Comment by ccaizergues** [comment]
Precisely @mccoys  I'm joining Celia team to work on this subject. Yet, technical implementation in Smilei is still not on his way.
As several reactions are involved, I should consider a non specific implementation. We could stay in touch on this subject.
For now, after a glance, I am still confused with the lot of constructors/dependencies.

For the option of creating neutrons or not, maybe something like :
"""
   If species atomic_number==0:
       if t<t_frozen: do not create
      else: move balistical
"""
The same can apply to electric charge :
"""
    if charge=0:
        if t<t_frozen: do not move
        else : move balistical
"""
