### ISSUE TITLE
AMcylindrical sources calculation

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#436]
Hi,

I am carrying out laser-target simulations with Smilei in the Amcylindrical geometry.

Till now, preliminary results do not seem physical,  due to very high fields and density values that develop on-axis as soon as the pulse arrive on the target. (and despite an already low time step value vs CFL).

One possible explanation could be related to the calculation of the sources.
Using Field diagnostic shows some positive contributions in the electron charge density map (whereas no such contribution appears in the corresponding particlebinning (x,r) diagnostic).

please see simplified case (no laser)
[pit10.py.txt](https://github.com/SmileiPIC/Smilei/files/7007148/pit10.py.txt)
.

Could you provide some treatment to prevent this effect, even when there is only a limited number of charged macro-particles per cell (situation which occurs during the beginning of the ionization front).

best

**Comment by beck-llr** [comment]
Hi
I am sorry but the `AMcylindrical` geometry is usually not appropriate for this kind of simulation where the laser hits a high density target. The reason is that the physics of the problem tends to quickly evolve towards a far from symetrical situations where many more modes are required. 

You could try to use more modes in order to check if that solves your problem. Sometimes 4 modes are enough but it highly depends on your parameters. It could simply not be possible.

 Also don't forget that the number of particles per cell along the theta direction that you use needs to be at least 4 times your maximum mode number. So in your case with 2 modes (m=0 and m=1) it is 4. With 4 modes it would be 12. That's why I highly recommend to use a `regular`  `position_initialization` and fix the number of particles along theta to be high enough (use `regular_number`).

In your case already, having only 10 particles per cell in total is barely enough ( that should give you 5 particles along theta, 2 along r and 1 along x).

I hope this helps !

**Comment by ccaizergues** [comment]
Hi,
Thanks for the propositions @beck-llr . I am performing new tests to see if this can solve the problem (for now it doesn't seem so).

Some point that I do not catch : when the laser  coming from xmin first hits the target (focalspot=20um), a shock wave seems to instantaneously emerge all along the x axis, then this wave propagates far faster than c (vr~4c).
How can this happen within the PIC treatment.

![Capture d’écran du 2021-08-19 09-38-18](https://user-images.githubusercontent.com/87831741/130029567-88022610-e976-4624-b28e-f0c3b84eb4a0.png)

**Comment by Z10Frank** [comment]
Does the result change using up to 4-5 azimuthal modes?

**Comment by Z10Frank** [comment]
Also, turning off the Poisson solver and with random positioning of the particles you may have forces like if you had a neutralising Species (see Section "A subtlety: ..." in https://smileipic.github.io/tutorials/advanced_wakefield_electron_beam.html) due to the initial local charge imbalance.

To try avoiding this effect, I suggest to keep the Poisson solver turned off and then initialising e.g. the ion Species superimposed to the electron Species (they have the same particles per cell so it is possible), using `position_initialization = 'eon'`

**Comment by ccaizergues** [comment]
I tested several of these solutions and other ones, but it was not enough for these simulations.

For what I remember:

Increasing the number of modes (beyond 2) enabled to prevent the unphysical shock propagating from the axis (by the way, I still can't figure how a 4c front wave can occur in a PIC simulation ; would enjoy the numerical explanation, if any ?)

With more modes, some high frequency (noise) high amplitude (>100TV/m) appeared on the axis during the simulation, which leaded to an unphysical hole in the target. (no clear improvement with much more particles or more modes (8) ).

Regular positioning partially reduced the noise but introduces modulation in the fields, and do not prevent the hole formation.
In fact, without pre-ionization regular positionning is not so usefull to preserve some symmetry.

I had issues with the Poisson solver (very slow / can't converge/ bug), so I turned it off.

I also wanted to test some filtering, but it does not seem to be implemented for now.

What is precisely done on-axis with the ```remove``` condition  for the particles ?


Probably I did not do much with preionized targets, so I can still test this.

**Comment by Z10Frank** [comment]
Have you tried perfectly superposing the Species (with `position_initialization = 'eon'` and Poisson solver turned off)?

No idea about the superluminal wave, a numerical instability will not necessarily be at v<c.

**Comment by beck-llr** [comment]
Particles live in 3D. There is no boundary condition applied on particles on axis because there is no need to.

**Comment by ccaizergues** [comment]
Effectively, there is no boundary condition to apply to the particles on axis. I was misled by the [0,r] grid for the fields, and also by the few available boundary conditions, that I believed related to on-axis difficulties. By the way, if the on-axis issue can be fixed, I then would be also interested in a thermal boundary treatment for the particles, if possible.
 
I think I already tried perfect superposition for front pre-plasma, probably also for the solid not preionized part, I should verify when tgcc reopen.
