### ISSUE TITLE
reduce collision cost

### ISSUE THREAD

**Issue by ccaizergues** [SmileiPIC/Smilei#444]
Hi Smilei developpers,

Some of my simulations appears to be slowed down in the collision bloc.

Would it be possible to process collisions not at each time step (then increasing the probability accordingly).
Which files should I Iook up to implement and test this modification.

**Comment by mccoys** [comment]
Hi,
It would be technically possible to implement, but there should be a lot of care doing this, because collisions are not well modeled when done less often (see parameter `s` in the theory).

If you want to implement this, look into `VectorPatch::applyCollisions` where the collisions are applied each timestep. You will also need to modify `Collisions::collide` where the `dt` value is currently set to `params.timestep`.

**Comment by mccoys** [comment]
Let me add that collisions typically double the time of the simulation. If it gets much higher, there is a problem in the setup

**Comment by ccaizergues** [comment]
Yes, I noticed typically 60% of computation time in this block, yet only with electron-electron collisions activated.
I think some time can still be saved in the patch/mpi setting, but not as much as expected with a reduced cost for collisions

**Comment by mccoys** [comment]
There is now a parameter `every` in Collisions. Be careful when using it
