### ISSUE TITLE
Particle merging memory error

### ISSUE THREAD

**Issue by Nikolai-mephi** [SmileiPIC/Smilei#469]
Dear smilei community,

I am trying to run a simulation on laser interaction with field ionization and particle merging options turned on. 
I am using smilei-v4.6. Here is the namelist and the .sh script I use to launch the simulation.
[namelist.txt](https://github.com/SmileiPIC/Smilei/files/7446603/namelist.txt)
[smilei.txt](https://github.com/SmileiPIC/Smilei/files/7446604/smilei.txt)

The simulation runs until the moment when the laser reaches the target, and then I get the following error:
[err.txt](https://github.com/SmileiPIC/Smilei/files/7446605/err.txt)

Previously, I ran it without the particle merging option, and it was fine and no errors occurred during the simulation, the only problem was that it was somewhat slow (that it why I decided to try particle merging).

So can I ask you, please, to explain what I might be doing wrong and what do I need to do to be able to run my simulation with particle merging?

**Comment by xxirii** [comment]
Hi @Nikolai-mephi,

There is indeed something wrong here but we will have to run again your namelist to see.

Nonetheless, I can suggest you some alternatives:
- Can you try with the Vranic spherical mode ?
- You have set the parameter `merge_min_particles_per_cell ` to 4 for all species but the ppc is above this value. I would set a larger value here.
- I would only put the merging on the species that grows, the electrons I guess in your case.
- I would start the merging only when the particle inflation starts because here you may have some merging occurring before the laser strikes the target.

I can't test for the moment unfortunately.

**Comment by Nikolai-mephi** [comment]
Thank you for the suggestions, @xxirii!

I will try to test them and let you know if they work.

**Comment by xxirii** [comment]
Hi @Nikolai-mephi, 

I have done some tests and I confirm that the code crashes also on my cluster. I have tested different options and it crashes also with the Vranic spherical.

**Comment by Nikolai-mephi** [comment]
Thank you for testing my namelist, @xxirii! 
I've made some tests myself and was able to get the simulation running past the point where it had previously stopped with the following namelist:
[namelist.txt](https://github.com/SmileiPIC/Smilei/files/7492613/namelist.txt)

However, I am not sure how it will behave for further timesteps. I will try to test it when there will be some spare computational resources available on my HPC cluster and report back here.

**Comment by xxirii** [comment]
Hi @Nikolai-mephi, I am still exploring your issue.

Can you tell me how you compile Smilei : 
- compiler
- type of processor
- flags or machine file

Thank you in advance.

**Comment by xxirii** [comment]
So I think I have a fix for you (tested with the Intel compiler). If you want I can generate a specific branch on the GitHub the time for us to make an official patch. What do you think?

**Comment by Nikolai-mephi** [comment]
Hi, @xxirii !

Thank you a lot for working on a fix! 
In response to your previous question - I compile smilei on E5-2680 Intel Xeon CPU by executing 'make' without any specific options using the following makefile:
[makefile.txt](https://github.com/SmileiPIC/Smilei/files/7608352/makefile.txt)

As for the specific branch - I do not think it is necessary right now. I am not in a haste with this simulation and can wait for the fix in the next patch. Once again, thank you very much!

**Comment by xxirii** [comment]
Fine, can you just confirm you use the Intel compiler behind mpi. You can get it by doing:
```
 mpicxx -show
```

I am asking because the problem comes from a vectorized loop that for an unknown reason does not provide the correct result with the Intel compiler. I did not see the problem using the LLVM compiler for instance. My fix is for the Intel compiler so far.

I will let you know when it is in the master version.

**Comment by Nikolai-mephi** [comment]
@xxirii ,
I am not sure if this is what you are asking for, but here's the output for 'mpicxx -show' command, or, to be more precise, for 'mpicxx.mpich -show' command, since in my makefile I have SMILEICXX ?= mpicxx.mpich:

g++ -Wl,-z,relro -I/usr/include/x86_64-linux-gnu/mpich -L/usr/lib/x86_64-linux-gnu -lmpichcxx -lmpich

**Comment by xxirii** [comment]
The bug is normally fixed in the new release. I will push additional corrections soon.
