### ISSUE TITLE
field ionisation

### ISSUE THREAD

**Issue by rl3418** [SmileiPIC/Smilei#470]
I'm trying to write code to model field ionisation with Smilei. I did not find an example script for field ionisation, so I read tst1d_05_tunnel_ionisation.py to comprehend what needs to be done to include ionisation. I'm a bit confused by the carbon mass which is normalised to 1836*1000. I guess the atomic number parameter takes the extra 6 into account, but I don't understand the factor of 1000. Also,  I just wish to check the ppc for electron should be set to 0 with no electrons at the beginning.

**Comment by mccoys** [comment]
`tst1d_05_tunnel_ionisation.py` is a good example for field ionisation.

The 1000 factor is simply to force ions to be very (unphysically) heavy so that the results can be compared to ideal analytical solutions.

The ppc for electrons should be set to 0 if the plasma is made only of neutral ions initially. If your plasma is already partially ionised, you should specify the electron population accordingly.

**Comment by rl3418** [comment]
That explains everything. Thanks for the clarification.
