### ISSUE TITLE
improve quality of plot

### ISSUE THREAD

**Issue by m-rezaei-p** [SmileiPIC/Smilei#508]
Dear All Experts,
I tried to compare the wakefield accelerator from neutral gas and per-plasma.
When I plot the Rho-electron plot, I do not know why the plot of neutral gas (bottom fig) it’s like a blur and not clear like per-plasma (top fig).
I attached namelist for  neutral gas([nature_gas.txt](https://github.com/SmileiPIC/Smilei/files/8054896/nature_gas.txt)) per-plasma([per_plasma.txt](https://github.com/SmileiPIC/Smilei/files/8054897/per_plasma.txt)) and compare image Rho-electron([Figure_1](https://user-images.githubusercontent.com/58806777/153737682-4e03b044-a679-4a9d-9131-78e38e7e81cf.png))
Do you think it is normal? 
how can I improve quality of neutral gas plot?
Thanks in advance,
Best regards,
Mohammad

[nature_gas.txt](https://github.com/SmileiPIC/Smilei/files/8054896/nature_gas.txt)
[per_plasma.txt](https://github.com/SmileiPIC/Smilei/files/8054897/per_plasma.txt)
![Figure_1](https://user-images.githubusercontent.com/58806777/153737682-4e03b044-a679-4a9d-9131-78e38e7e81cf.png)

**Comment by Z10Frank** [comment]
Hello, 
the results in the second Figure seem ok from a first look. To reduce the point-like noise, can you try increasing the number of particles `nppc`, e.g. to 9, 16, 25 and see how it changes? Remember that in your first figure you are using electrons that are initially positioned regularly (`position_initialization="regular"`), while in the second figure your density is given by electrons generated randomly from the ionization process, so it's normal that the second one will have a point-like noise. To have an idea of the difference caused by the `position_initialization`, try to obtain the first figure but using a `position_initialization="random"`.

In your first figure I see some modulations in the wake zone, to reduce them I would try to change the longitudinal resolution ( `dx< lambda0/25`). I don't know if you need a very fine transverse resolution for your studies, but for a first exploratory study even `dy=lambda0/2` should correctly simulate your wakefield generation and the ionization. In this case, with dx different from dy, the Courant condition for `dt` becomes `dt<1./sqrt(1/dx**2+1/dy**2)`. This condition becomes dt<dx/sqrt(2) like in your namelist when `dx=dy`.
