### ISSUE TITLE
Saving a timetrace: (i) DiagProbe slow, (ii) Subgrid leads to 'Segmentation fault'

### ISSUE THREAD

**Issue by illia-thiele** [SmileiPIC/Smilei#53]
Dear Smilei community,

I would like to save a timetrace of a field component at certain spatial points. To this end, one can use either the probe diagnostocs 'DiagProbe' or the field diagnostics 'DiagFields' using the subgrid feature. Both led in my case to unsatisfactory results:

(i) Using DiagProbe:
I have noticed that adding the diagnostics
DiagProbe(
    every = 1,
    origin  = [L0x/2., L0y/2.],
    fields = ["Ey"]
)
slows down my simulation with 256x256 spatial points in 2D (only Maxwell, no particles) by a factor of 34. Did you ever noticed this problem?

(ii) Using Subgrid:
I have tried to use the 'DiagFields' diagnostics with the subgrid feature in many different ways, but always got a Segmentation fault:
DiagFields(
    every = 1,
    fields = ['Ey'],
    subgrid = s_[128, 128]
)
Also using
'subgrid = s_[128:129:1, 128:129:1] '	->	Segmentation fault
'subgrid = s_[128:130:1, 128:130:1] '	->	Segmentation fault
'subgrid = s_[128:130, 128:130]'		->	Segmentation fault
Only using the subgrid feature with 'subgrid = s_[::2, ::2]', i.e., reducing the number of written points but not the domain, works properly. I am doing s.th. wrong or is there a bug?

Very best regards
Illia

**Comment by mccoys** [comment]
(1) DiagProbe

The slowdown might be due to your "every = 1" which tries to write out data to the filesystem every iteration. The code waits for the writing to be finished before continuing.
To avoid waiting, there is the option "flush_every" that you may use to *flush* the data less often (it will stay in some buffer for a while). I suggest every 100 or 1000 iterations. This speeds up the simulation, but might cause loss of data in case of a crash.
Please report on success or failure if you try this option.

(2) DiagFields

This may be my fault: I implemented the subgrid feature. I never tested it with 1 point, but it should work with 2 points. Could you try another point that 128 ? I will investigate as soon as I can.

**Comment by mccoys** [comment]
Thank you for the input file.

Let's keep the issue open as a reminder to fix the segfault. I will investigate.

**Comment by mccoys** [comment]
The subgrid segfault should be fixed now.
