### ISSUE TITLE
Adding time dependence to "space_time_profile_AM"

### ISSUE THREAD

**Issue by m-jirka** [SmileiPIC/Smilei#548]
Dear SMILEI developers,

I can not figure out how I can add time dependence to 

> space_time_profile_AM

in input file for creating a generic wave?

If I define e.g.
`def Br_mode0(x,r,t): return complex(x*r*t)`
I would get an error saying:
> [ERROR](0) src/Profiles/Profile.cpp:269 (Profile) Profile `Laser[0].space_time_profile[0]`: does not seem to return a correct value
  On rank 16 [Python] TypeError: Br_mode0() takes exactly 3 arguments (2 given)

Did I miss something in the manual?

Thank you,
m-jirka

**Comment by mccoys** [comment]
Let's keep this issue until the doc is clearer.

**Comment by Hedvika** [comment]
Dear Smilei developers,

I am also working on this problem with m-jirka. I/we do not understand your answer.

I want to explain our problem once again with more details to make the problem clearer.

We are trying to use the cylindrical coordinates,  _[geometry = "AMcylindrical"]_, and define
the profile of the electromagnetic wave as 

_[ Laser(
    box_side = "xmin",
    space_time_profile_AM = [ Br_mode0, Bt_mode0],
)
]_

where we have used the following functions with time dependence:

**def Br_mode0(x,r,t):
    return complex(something(x,r)) * np.cos(t+phi0)

def Bt_mode0(x,r,t):
    return complex(0.0)**

The simulation finishes when we comment out the term [np.cos(t+phi0)]  with time t.
When we try to use the full expression Br_mode0(x,r,t), the simulation fails with the error mentioned above:

**[ERROR](https://github.com/SmileiPIC/Smilei/issues/0) src/Profiles/Profile.cpp:269 (Profile) Profile Laser[0].space_time_profile[0]: does not seem to return a correct value
On rank 16 [Python] TypeError: Br_mode0() takes exactly 3 arguments (2 given)**

We have concluded that the time variable is ignored or lost somewhere during the runtime.

It might be caused by:

1. There is a mistake in the code implementation and the documentation is correct.
2. The code is good and the time dependence is there but the documentation is badly written/or we 
 misundertood the written instructions.

We havent found anywhere some examples of input file where is showed the usage of the Laser section for
AMcylindrical mode/coordinates with time dependence. 

I have found only the input file [Smilei/benchmarks/tstAM_16_multiple_envelopes_wake.py],
where the  wave envelope is implemented with time dependence. The time dependence is 
definitely used (see functions  gaussian_beam_with_temporal_profile(x,r,t,i_envelope), summed_envelope_profiles(x,r,t)).
Or there are examples on AMGaussian, which is implemented very differently and we can not use it a template.

We would be grateful for some clarification on this issue/ or advise on what to do next.

Thank you for reading and patience!

Hedvika

**Comment by mccoys** [comment]
What I meant previously is that the coordinates should be `(r,t)` as the profile cannot depend on x. The laser injection is only at the boundary (x=0).

**Comment by Hedvika** [comment]
Dear mccoys,

thank you very much for your answer. It appears that it solves our problem and we were able to run the simulation with reasonable results. 

So far so good! 

Thank you again,
Hedvika

**Comment by mccoys** [comment]
@Z10Frank @beck-llr Is it possible for you guys to fix this point in the doc?
