### ISSUE TITLE
-lintl error on supercomputer

### ISSUE THREAD

**Issue by chiehjen-jerry** [SmileiPIC/Smilei#597]
Hello:

    I tried to install smilei on g100 of CINECA, but failed so far. 
   The main problem is: Once the python module is loaded, it creates an invalid link "-lintl" to the makefile environment, and causes the compiler to quite. The error message is: 
Linking smilei
/usr/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status
 
I don't know what "intl" stands for or if it's necessary. In another machine (Karolina), the "-lintl" doesn't appear and the code compiles well. Does anyone encounter this problem before? Or do you know any way to bypass this issue?

The link can be checked, after loading each module by:
make env 

Thank you in advance.

**Comment by beck-llr** [comment]
Hi

I suggest to try to contact CINECA's support and get help from them. This looks like a problem related to the environment and not to the code itself. It will be very difficult for us to help without having access to the system ourselves.

If you manage to find a good combination of modules that works for G100 let us know so that we can add it to the list. It could help someone else having the same issue in the future.
Cheers

**Comment by chiehjen-jerry** [comment]
Hi:

    Thanks for the info. I have installed smilei on g100 of cineca 
successful now. The modules to load are:

module load spack
spack load ***@***.***
module load intel
module load intelmpi
module load hdf5/1.10.7--intel-oneapi-mpi--2021.4.0--intel--2021.4.0


---
Sincerely,

Chieh-Jen (Jerry) Yang
