### ISSUE TITLE
Strange Minimum memory consumption in Smilei output and Crash after 2467 Timesteps 

### ISSUE THREAD

**Issue by mpikzink** [SmileiPIC/Smilei#601]
Dear All,

as the title says we keep having a weird behavior with smilei: basically it crashes always after the same timestep (2467). By looking at the output file we noticed this 

in our setup:
```
Python 3.9.6
g++ (GCC) 12.1.0
openmpi-4.1.4-gcc-12.1.0
HDF5 version 1.12.2 (parallel)
Python version 3.9.6
Version: 4.7-148-g8877fbc95-master
MPI_THREAD_MULTIPLE enabled
Number of MPI processes: 32
Number of threads per MPI process : 8
we also use SLURM as Node Workload Manager
```
We get a strange output in the diagnostics. There are two lines with negative memory consumption.
```
 Minimum memory consumption (does not include all temporary buffers)
 --------------------------------------------------------------------------------
              Particles: Master 64 MB;   Max 395 MB;   Global 5.07 GB
                 Fields: Master 2470 MB;   Max 2470 MB;   Global 77.2 GB
            scalars.txt: Master 0 MB;   Max 0 MB;   Global 0 GB
    ParticleBinning0.h5: Master 0 MB;   Max 0 MB;   Global 0.0238 GB
    ParticleBinning1.h5: Master 0 MB;   Max 0 MB;   Global 0.00954 GB
    ParticleBinning2.h5: Master -1983 MB;   Max -1983 MB;   Global -62 GB
    ParticleBinning3.h5: Master 0 MB;   Max 0 MB;   Global 0.00954 GB
    ParticleBinning4.h5: Master -1983 MB;   Max -1983 MB;   Global -62 GB
    ParticleBinning5.h5: Master 0 MB;   Max 0 MB;   Global 0.0238 GB
    ParticleBinning6.h5: Master 0 MB;   Max 0 MB;   Global 0.0238 GB
    ParticleBinning7.h5: Master 0 MB;   Max 0 MB;   Global 0.0238 GB
    ParticleBinning8.h5: Master 0 MB;   Max 0 MB;   Global 0.0238 GB
             Fields0.h5: Master 0 MB;   Max 0 MB;   Global 0 GB
        Performances.h5: Master 0 MB;   Max 0 MB;   Global 0 GB
```
we do not know if this may play a role in the behavior, but the current simulation has been relaunched starting from a previous checkpoint. 
We also tried to tweak the diagnostics by changing the `every` option. By doing this we noticed that when putting the loadbalancing's `every` to 2, the crash occurs much earlier.
[smilei_crash.txt](https://github.com/SmileiPIC/Smilei/files/10706210/smilei_crash.txt)

**Comment by mccoys** [comment]
This is a memory error. Load balancing requires to exchange significant amounts of data, so that it temporarily duplicates chunks of data for the exchange. It may happen that a given process receives/sends too much to hold all buffers. You could try, for instance, to increase the number of threads and decrease the number of MPIs, if possible.

Concerning the diagnostics, I don't believe it is related, and I would need your input script to see what is going on.

**Comment by mpikzink** [comment]
[beam_fields_reconstruction_Au.txt](https://github.com/SmileiPIC/Smilei/files/10709930/beam_fields_reconstruction_Au.txt)

**Comment by mccoys** [comment]
Ok one issue is that your problematic particle binning diagnostics are awfully large (if I'm correct, buffers of about 2.3 GB each, above the limit for 32-bit signed integers). That is probably why the memory display is faulty, but it does not mean the diagnostic is actually wrong.

The real problem is likely your very high number of particles. Several billion is too much for 256 cores. You would need at least 10 times more.
