### ISSUE TITLE
Maxwell solver for suppressing numerical Cherenkov instability

### ISSUE THREAD

**Issue by HaoPengYY** [SmileiPIC/Smilei#626]
Dear Developers,

Hi. I tried to simulate the free traveling of a relativistic electron beam (REB) in 2D geometry, a moving window with the velocity c along the propagation direction is used. As the simulation goes, severe numerical Cherenkov radiation can be seen with the default maxwell solver-the 'Yee' solver. In order to suppressing this unphyiscal radiations, I tried other solvers introduced in the manual of SMILEI. 

But I found that 'M4' solver does not work at all, 'Lehe' solver collapses in the moving window (the fields go randomly like what we see when the CFL condition is not fulfilled, I use dt=0.999/(1/dx^2+1/dy^2) here). 'Cowan' solver is "under development, not yet working", but it should work according to the manual (I just update my SMILEI several days ago). 'Bouchard' solver seems to work very well in the moving window and with 'silver-muller' boundary conditions (something not physical happened when using the 'PML' boundary conditions), but the results are very different from the same simulation with 'Yee'.

So, my questions are, why are these happening? Can I trust the results by 'Bouchard' solver? Which solver do you recommend in this case? Thanks a lot in advance.

**Comment by Z10Frank** [comment]
Hello, 
thanks for reporting these issues, I am not sure PML can work properly with solvers that are not `Yee` (@beck-llr?)

I know that in 2D the fields of a relativistic electron bunch become particularly high at the borders, so I guess PML are necessary. Using `AMcylindrical` or `3Dcartesian` geometry would also help creating more realistic fields for the electron bunch.

I would like to perform some tests with the B-TIS3 interpolation scheme in my branch to reduce the effects of Numerical Cherenkov radiation (https://www.cambridge.org/core/journals/journal-of-plasma-physics/article/abs/improved-modellisation-of-laserparticle-interaction-in-particleincell-simulations/4758CAE0D68B925D7BD7C71E532BF41A), do you have a minimal namelist to start from? I hope to merge this branch to the develop branch as soon as possible, especially if it works also in your case.

**Comment by Guilleaumes** [comment]
Bouchard Solver should work properly with SM boundary condition, but I recommand you to test it because it's not a standard solver and some error can subsist even after a lot of testing. You can find numerical example in this thesis manuscript : https://theses.hal.science/tel-02967252 (p 109)

You have to ensure dt=0.5dx : using "magical timestep" will kill all high order Numerical Cherenkov Instability.
Bouchard solver ensure that there a "no" numerical dispersion between 0, and kmax/2 (in fact c = 1.01 at kmax/2) for all direction.

For high frequency, light speed become less than one and you can have numerical cherenkov radiation if you have current at theses frequencies (above kmax/2). The tips is to use a current filter to kill high frequency current and aliasing.

For PML, some recents modifications have been made to use it with high order FDTD, Moving Windows and Single Domain Multiple Decomposition and 3D. It will be release soon.

**Comment by Z10Frank** [comment]
@Guilleaumes could you write this information in the `maxwell_solver` entry of the `Main` block documentation in the `Write a namelist` page https://smileipic.github.io/Smilei/Use/namelist.html#maxwell_solver?

**Comment by HaoPengYY** [comment]
@Z10Frank @Guilleaumes Thanks for your quick replies and sorry for the late response. I will try to provide a namelist ASAP. Currently, Bouchard solver seems to work fine, but I am concerned that it has differences with the same simulation with Yee solver. These solvers are all based on the modified FDTD algorithm, the spectral solver PSATD seems not available now with SMILEI. Maybe I can compare the results with those from WarpX.

**Comment by Z10Frank** [comment]
@HaoPengYY You may want to try also the B-TIS3 scheme by P.-L. Bourgeois and X. Davoine to reduce the effects of numerical Cherenkov radiation without a spectral solver: https://www.cambridge.org/core/journals/journal-of-plasma-physics/article/abs/improved-modellisation-of-laserparticle-interaction-in-particleincell-simulations/4758CAE0D68B925D7BD7C71E532BF41A 

The scheme was recently pushed in the `develop` branch. Let me know if you need help in testing the scheme for your cases.

**Comment by Z10Frank** [comment]
I still recommend the use of `AMcylindrical` geometry and `PML` boundary conditions to obtain physically meaningful results in your cases.

**Comment by HaoPengYY** [comment]
@Z10Frank Thanks a lot, I will try to think about this. By "using AMcylindrical" and "PML", do you mean that I do not use moving window but AMcylindrical geometry instead? But the geometry I am modelling is not cylindrically symmetric.

**Comment by Z10Frank** [comment]
Hello, you mentioned 3 independent concepts. 
The moving window is available in all geometries.
PML are boundary conditions, they are available in 2D, 3D and AMcylindrical, the geometries that could be suited for your case (to discuss).

The AMcylindrical geometry is for systems close to cylindrical geometry. Deviations from perfect cylindrical geometry can be taken into account adding more azimuthal modes: https://smileipic.github.io/Smilei/Understand/azimuthal_modes_decomposition.html

I suggest this geometry instead of 2D cartesian in case you need to use also the self-consistent field of the bunch.
In 2D cartesian, it can be high at the borders and difficult to manage: https://github.com/SmileiPIC/Smilei/issues/137
This is not an issue of the code, it happens when you solve relativistic Poisson equation in 2D cartesian.

In 2D cylindrical the results would be more similar to 3D if your case is close to cylindrical symmetry and fields would decrease more quickly towards the borders. These high fields are the reason why I recommend PML boundary conditions, to reduce reflections.
