### ISSUE TITLE
Tasks Parallelisation

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#695]
I'm interested in using the `Tasks Parallelization` feature. According to the documentation, it appears that just explicitly setting `cluster_width` in the `Main` block of a `Namelist` should enable this feature if `OpenMP 4.5` or later is supported. I looked in `benchmarks/tst2d_02_radiation_pressure_acc.py` for understanding the changes in the `Namelist` for `Tasks Parallelization` but couldn't find more information.

I'm using Intel 2021.4 and onward compilers and according to intel they should support `OpenMP 4.5`. But when I run simulations, I always see `OpenMP task parallelization not activated`. So what one needs to do for enabling  `Tasks Parallelization` feature? Is there a compatibility/incompatibility issue with geometry,  and other features `vectorization`, and `SDMD` etc?

**Comment by Z10Frank** [comment]
Hello,
to activate task parallelisation, you need to use `config=omptasks`.

Normally it is compatible with all geometries, but I am not sure that it is compatible with vectorisation, SDMD or other advanced features.

Task parallelisation is an experimental feature and unfortunately in case of related issues we will likely not progress rapidly because there are other more pressing developments to implement. This is one of the reasons why this mode was removed from the print obtainable with `make help`.

**Comment by Tissot11** [comment]
Thanks for the answer. Indeed, there is incompatibility with `vectorization` and `SDMD`. Please close this issue.
