### ISSUE TITLE
Long running times with Hilbert curve patch distribution

### ISSUE THREAD

**Issue by GeorgeHicks1** [SmileiPIC/Smilei#72]
Hi,

I have compared the running time for a thin foil simulation in smilei. I first used the default hilbert curve patch distribution and noticed the simulation was very slow compared to other PIC codes I have used. I changed to using rectangular MPI regions using "patch_arrangement = "linearized_XY"" and the running time improved by 5 times.

Unfortunately, I can't use load balancing when using rectangular MPI regions, so wonder if I can run these simulations faster with a correctly set-up hilbert curve patch distribution. Although you do say "Depending on the plasma shape, the MPI regions shapes which follow the hilbert curve (as described above) may not be efficient in all cases. " All my particles I confined to a very thin region in the centre of the simulation box.

I have attached my namelist, log file and submission script. Please can you advise if this is normal behaviour and if there is anything I can do to improve the speed of the hilbert curve simulations?

Thanks,
George

[hilbert.zip](https://github.com/SmileiPIC/Smilei/files/2616729/hilbert.zip)
[linear.zip](https://github.com/SmileiPIC/Smilei/files/2616726/linear.zip)

**Comment by beck-llr** [comment]
Hi George and thanks for your report.
The problem you are facing is a well known one and might be a bit under documented on our website. Sorry about that. The thin-foil case is the exact reason why we setup the "linearized_XY" patch arrangement which is much better in that particular case since it forces the code to remain in an almost perfectly balanced state at all times wheras the Hilbert curve goes completely crazy.

But there might be a few things you can try in order to get an even better balance.  You could try to use the openMP dynamic scheduler by `export OMP_SCHEDULE = DYNAMIC`. If, as I presume, you're running on a single dual socket node, you can also enlarge your MPI domains by using only 2 mpi processes instead of 4 ( 1 per socket) and double your number of openMP threads ( 24 instead of 12). 

The result probably won't be very different since the "linearized_XY" patch arrangement already kind of force an almost perfect balance but it is worth a try.

Good luck and please keep giving us feedback of your tests !

**Comment by beck-llr** [comment]
Hi George
Just so you know, I tried running your namelist with the setup I suggested (2 MPI, 24 openMP) on a single dual socket skylake node (Irene skylake) and the simulation terminates much quicker than what your log shows:

```
11500/11580     5.3299e+02     4.5917e+03   (  4.5997e+01 )
 

 End time loop, time dual = 536.694
 --------------------------------------------------------------------------------
 

 Time profiling : (print time > 0.001%)
 --------------------------------------------------------------------------------
 Time in time loop :    4625.128    96.714% coverage
               Particles    2809.675    60.748%
                 Maxwell    468.934 10.139%
             Diagnostics    478.495 10.346%
              Collisions    0.158   <1% 
          Sync Particles    369.437 7.988%
             Sync Fields    92.470  1.999%
          Sync Densities    224.888 4.862%
         Reconfiguration    2.237   <1% 
```
That is  a speed up of roughly 2.5 compared to your run. I doubt that going to the dynamic scheduler explains such a large difference. Make sure your openMP threads are properly pinned to separate cores and that you compiled Smilei with the proper flags for vectorization.

Keep Smileing

**Comment by mccoys** [comment]
Solid foil targets are quite tricky to balance correctly. In my cases I can reach a computation time per particle per iteration, normalized to 1 core, of 0.5 ns, diagnostics included. Compare your numbers to that one in order to find out if you are well optimized.
In addition to the advises above, try modifying the size of patches. I noticed that, often, there is no use having patches smaller than 100x100, and can actually cause slowdown. There is an optimal patch size that depends on each simulation.

**Comment by GeorgeHicks1** [comment]
Thank you both for your comments.

@beck-llr, as detailed [here](https://github.com/SmileiPIC/Smilei/issues/71) I tested varying the MPI/OMP combination and found 24 MPI and 2 OMP to be the best combination. However, the speed-up is only 7% compared to the 48 MPI and 1 OMP case. I got a small boost (3%) from using the dynamic OMP scheduler. I assume the huge speed-up you encountered is due to different hardware, but thank you for taking the time to run it.

@mccoys I have compared my normalised computation time to you. I have:
- computation time=10428s
- 90327808 particles
-  11580 iterations
- 48 cores

This gives me a normalised time of 0.48µs which matches your time very well.

Thanks again to both of you for your help.

**Comment by mccoys** [comment]
I you have obtained a significantly better performance on the same machine with another code, we would be interested to know some details in order to investigate the reasons.

When comparing, make sure the disk outputs are accounted for.

**Comment by GeorgeHicks1** [comment]
I haven't had significantly better performance. I ran the same simulation in [EPOCH],(http://www.ccpp.ac.uk/codes.html) which ran at 97% the speed of the optimised smilei simulation.

**Comment by beck-llr** [comment]
Might I ask more details on the hardware you are using ? Because a speed up of 2.5 is really a lot and can probably not be explained by hardware alone unless you are using a computer from 2010 but they didn't have cpus with 24 cores back then ...

**Comment by beck-llr** [comment]
Ok I've just seen your other post in which you detail your system. You are actually using hyper threading when I used 48 physical cores which explains the difference. I strongly advise against hyper threading as @jderouillat already wrote you.  You should try  using only 12 openMP threads and 2 MPI ranks.

**Comment by GeorgeHicks1** [comment]
Thanks, I am trying a job now requesting:

`#PBS -l select=1:ncpus=24:mem=125000mb:mpiprocs=2:ompthreads=12`

I'll let you know how it goes

**Comment by beck-llr** [comment]
Let's just hope that PBS is intelligent enough to place the MPI ranks on different sockets by default.

**Comment by mccoys** [comment]
@GeorgeHicks1 any news ?
