### ISSUE TITLE
PML for magnetized plasmas

### ISSUE THREAD

**Issue by fyli16** [SmileiPIC/Smilei#733]
Hello developers, a quick question about using PML boundary condition with magnetized plasmas: My initial test shows that PML works pretty well for unmagnetized plasma, especially when I choose a sufficiently large number of cells for the PML layer. But for magnetized plasma (with a background B field across the domain), PML seems to completely fail, causing messy wave and plasma dynamics. Could this be possibly due to discontinuity in the B field between the physical domain and the PML domain? Any suggestions on how to apply PML to magnetized plasmas. Thank you.

**Comment by beck-llr** [comment]
Hi
You are absolutely correct, this is an identified shortcoming of the PML. This is still under investigation but a possible work around is to use `Prescribed fields` instead of `External Fields` to describe the magnetic background.
Particles are still affected by the background B field but it is not taken into account during Maxwell's equations resolution and therefore does not generate unphysical discontinuity within the PML.

Make sure that the magnetic field you introduce is divergence free otherwise you will get incoherent results though. You may also experience a drop in performance unfortunately.

Please let us know how this works for you.

**Comment by fyli16** [comment]
Hi @beck-llr , Thank you for introducing a possible workaround! I am testing this out and will update here on the outcome.

**Comment by fyli16** [comment]
PrescribedField works as expected. Closing this now.
