### ISSUE TITLE
TrackParticles diagnostics using filter with a random subset

### ISSUE THREAD

**Issue by srozario121** [SmileiPIC/Smilei#74]
Hello,
I've been using the TrackParticles diagnostics and I can't seem to use the filter argument to select a random subset of particles that the filter diagnostic picks up. I want to extract (say 1000) randomly chosen trajectories from those that have the correct momenta for any previous time.

I'll give an example to explain what I want. 
Consider a LWFA simulation using SMILEI.
The plasma wave has some velocity. I want the trajectory of particles which are faster that the plasma wave. 
px>beta_plasmawave.

Now there might be loads of particles. So I want to pick some particle trajectories from these. Maybe 1000 random trajectories? But from what I understand about the filter diagnostic it only checks the particle parameters at a particular time and evaluates whether or not to dump the position? So I can't keep randomly picking at every timestep otherwise I will get particle trajectories from different particles at every timestep. 
Please correct me if I've mis-understood how this works.

I could do this using the post-processing step with the 'select' parameter in happi, but my particle tracking diagnostic is huge (100GB..) 

Any suggestions on how to do this are much appreciated!
Thanks
Savio

**Comment by mccoys** [comment]
You have properly understood the way the `filter` argument works. It only matches particles properties at a given time. If you want to select particles according to their whole history, then you have no choice but to post-process. This make sense because, during the simulation, it is not possible to know what will happen in the future of each particle.

There is one trick though. In Smilei, tracked particles are given a non-zero `id` (a label, which is a number) only when they have been successfully `filter`ed previously. Consequently, you can use the `filter` function to check whether the particles have an `id` or not. Here is an example:

```python
def my_filter(particles):
    return (particles.px>beta_plasmawave) + (particles.id>0)
```

Note that the `+` corresponds to the logical `or`.
This will select particles with large-enough `px`, then keep selecting the ones that have been selected previously.

Some more advanced manipulation of the particles ID is possible: http://www.maisondelasimulation.fr/smilei/ids.html

**Comment by srozario121** [comment]
Ah i see! Thanks I'll try this. I'll close this now.

**Comment by srozario121** [comment]
I was not particularly successful in implementing a random subset...
If I understand how this diagnostic works, the random sub-selection has to be done during post-processing. But if your diagnostic file is huge, the sorting takes an impractical amount of time.
Sorry! Maybe the developers can help you

**Comment by mccoys** [comment]
@0xDBFB7 Please explain what filter you wish to implement.

A typical example would be
```python
def keep_high_energy(particles):
    return particles.px**2 + particles.py**2 + particles.pz**2 > 10.

DiagTrackParticles(
    ...
    filter = keep_high_energy
)
```

**Comment by mccoys** [comment]
@0xDBFB7 have you solved your problem? Please open a new issue with more details on your needs otherwise.

**Comment by 0xDBFB7** [comment]
@srozario121 Very sorry for the late reply, I was away from my computer - I think the code block you provided will do just fine.

Thanks for such a brilliant piece of software @mccoys et al!
