### ISSUE TITLE
Question about the units

### ISSUE THREAD

**Issue by emil-mouz** [SmileiPIC/Smilei#82]
Hello, i need some help with the unit converter in post-processing. I try to understand from the manual how I can change the units in post-processing, but I haven't manage it yet. I installed the module pint and I imported as the manual said in ipython/
Here is a picture of what I type in order to illustrate a simple example

![screenshot from 2019-02-04 12-51-48](https://user-images.githubusercontent.com/45740200/52204405-ba68d900-287c-11e9-942c-22940a116207.png)

Thank you in advance!

**Comment by mccoys** [comment]
You are trying to convert to m/s, which is not a unit of energy ! Then of course the conversion cannot be made. Try `J` for joules.

You must also make sure that your simulation contains the keyword [reference_angular_frequency_SI](http://www.maisondelasimulation.fr/smilei/namelist.html#reference_angular_frequency_SI). Otherwise, you may define it in the post-processing as described [here](http://www.maisondelasimulation.fr/smilei/post-processing.html#open-a-simulation).

**Comment by emil-mouz** [comment]
Thank you

**Comment by mccoys** [comment]
I forgot to mention that you may also add other units for the axis: in your case, seconds. This would give `units=["J", "s"]`

**Comment by emil-mouz** [comment]
I want for example to see the Ex in units let's say V/m but written in dictionary.
 I wrote the following

ex=S.Field(0,"Ex",units={"x":"um","y":"nm"})
ex.plot(figure=4)

With the above script I can only see units in x,y axis, but not units for Ex field.
 How can I include them?

**Comment by emil-mouz** [comment]
No, thank you very much.

Στις Τρί, 5 Φεβ 2019 στις 2:25 μ.μ., ο/η mccoys <notifications@github.com>
έγραψε:
