### ISSUE TITLE
DiagFields storage estimation with subgrid

### ISSUE THREAD

**Issue by illia-thiele** [SmileiPIC/Smilei#85]
Dear SMILEI team,

the estimation of the data which is produced by a diagnostics in the output file is a very useful tool. However, I have realized that when using DiagFields with a subgrid, for example like here

DiagFields(
    every = [10000,10],
    flush_every = 1000,
    fields = ['Ex','Ey','Bz_m','Jx','Jy','Jz','Rho'],
    subgrid = s_[3946:4076, 5738:7574],
    time_average = 5,
)

then the estimation seems to be a way too large. I have simulations where the estimation is about 100 times too large. Without using the subgrid option, the estimation works well. Is it possible that the estimation does not take into account the data amount reduction due to the subgrid option?

As a side remark: I have realized that diagnostics as in the example above, with a subgrid writing down the field at many timesteps, slows down the simulations quite a lot, even when using flush_every. I am running 2D simulations for 7h on 1000 procs without such a field diagnostics and break the wall-time limit of 24h when I try to have this diagnostics. Could you give me an idea how to speed up the simulation with this field diagnostics?

Very best regards
Illia

**Comment by mccoys** [comment]
Indeed there seems to be some error in calculating the disk space. I will look into it.

Concerning the slow output of field diagnostics, it is a known issue, and we do not have a clear way to speed it up. However, we recommend using Probes, which are a providing a very close information, and are much faster to output. The only difference is that the probe fields are interpolated with the same interpolation method as the particles, instead of being the exact fields on the grid.

**Comment by mccoys** [comment]
@illia-thiele I have done some corrections for the disk size estimate. I think I should be able to push these modifications to the github soon. Indeed, the subgrid was not correctly taken into account (at all).

Have you managed to increase the performances using probes ?

**Comment by mccoys** [comment]
@illia-thiele The latest pushes should fix the disk size estimate.

I'm also interested to know if Probes work for you.
