### ISSUE TITLE
Problem about pressure

### ISSUE THREAD

**Issue by prlWanted** [SmileiPIC/Smilei#91]
Hello. I am trying to get the local electron temperature along the x axis from the electron phase space by using a ParticleBinning to record the pressure like this:
![image](https://user-images.githubusercontent.com/22358113/54215756-c0d81980-44e8-11e9-9be8-7344aeb323bb.png)
So I should be able to get the pressure with: S.ParticleBinning(indexOfParticleBinning). Because we have:
![image](https://user-images.githubusercontent.com/22358113/54216879-c5053680-44ea-11e9-861f-afe679ab7cf7.png)
It is reasonable to think that the unit of P should be Nr*me*c^2. So I use the pressure times the local density and 511 keV, I got this:
![image](https://user-images.githubusercontent.com/22358113/54217005-16adc100-44eb-11e9-859d-7a9b3680c953.png)
Which agrees well with my fluid simulation. I felt good.

But, yesterday, I updated my SMILEI with git pull and make. Then this is not right more. The temperature is about 25 times larger. I don't understand.

**Comment by prlWanted** [comment]
New: I used another ParticleBinning like this:
![image](https://user-images.githubusercontent.com/22358113/54218576-2549a780-44ee-11e9-8725-aa30ffd620bc.png)
just to record the weight. And I equal Te=pressure/weight. Now it seems good. But I still want to know how do I get the temperature with a single ParticleBinning for the pressure. Thank you very much!

**Comment by mccoys** [comment]
The second technique you tried is correct. You need to divide by the sum of weights. There is no other way.

Note that happi can compute directly the division, using for example ``"#0/#1`` as the diagnostic number.

Concerning your update of smilei, we have recently changed the definition of the weights. This explains why you obtained a different result after the pull.

**Comment by prlWanted** [comment]
Thank you very much! But do you mean that I can use a single probe with deposited_quantity="weight_vx_px/weight"? to get the temperature?

**Comment by mccoys** [comment]
No. You still need 2 diagnostics in the input file. The division is computed as post-processing in the `happi` tool.

**Comment by ywppku** [comment]
Dear @prlWanted and @mccoys ,

I am using this method to check the temperatures in my simulation.
While the electron temperatures are reasonable, the ion temperatures seem too high.

I guess when I use `deposited_quantity = "weight_vx_px"` for the ion ParticleBinning diag., since the momentum of ion is also normed by me*c, I should divide the weight, as well as the ion mass?

In general, I have some doubts about the temperatures in PIC simulation, how should we define and calculate the plasma temperature from PIC? Using the standard deviation of velocity? Or to fit the energy spectrum by the Maxwellian distribution of each species? 
And why we don't have a temperature diag. in Smilei?

Thanks in advance.
